#+TITLE: The best place to work by Ron Friedman
#+FILETAGAS: :Management:

* Problem statement

  A Gallup poll has found that 70% of Americans are disengaged from
  their work. Although management in most companies recognize this
  problem, they have been going about fixing the problem the wrong
  way. This is partly due to reliance on manufacturing methods like
  Taylorism that do not make sense for today's knowledge workers.


* Lessons of failure

  High achievers fail multiple times and make a lot more attempts than
  others. Workplaces should not encourage individuals to do the same
  thing over and over. Experimentation is necessary in today's
  climate.


* Lessons of workspace design

  Introduce elements from nature such as seating next to large
  windows, aquariums, plants etc.

  Modern workspaces provide opportunities for different types of
  activities e.g. cubicles for distraction-free work, open spaces for
  collaboration etc. This is often called providing caves and campfires.

  Employees should have the opportunity to personalize their office
  setting. A comfortable, personalized space can help improve
  productivity. This is one of the key reasons people like working
  from home.

  There should also be plenty of opportunities to step away from the
  office space to allow the brain to recharge.


* Lessons of distractions and play

  Modern leaders should consider themselves less as designers and more
  as gardeners who help the seeds of ideas in employees' minds grow.

  The subconscious mind is better at processing complex problems. Taking
  30 min to step away from a problem can lead to more insights.

  Distractions can also help. Hence, it is worthwhile to have book
  clubs or TED talk discussions for the organization. Similarly,
  physical exercise can lead to improved complex task processing. Make
  time for these in company schedules.


* Lessons of happiness

  When the team needs to think big-picture or to brainstorm, then
  starting with good news that makes the team happy can improve
  output. However, this does not help with careful analysis or
  troubleshooting.

  Modest but frequent positive experiences (positive feedback from
  managers, high-quality espresso every day, catered lunches
  occasionally) can have a greater impact on employee wellness than
  large infrequent positive experiences.

  Haev occasional forums where people express gratitude for the things
  that go well. For instance, you can have a meeting dedicated only to
  the accomplishments over the past month rather than the gaps or
  delays.


* Lessons of friendship

  Employees feel more connected to work when they have strong
  friendships at work. Find opportunities for employees to connect on
  common interests.

  People connect closely based on the following factors.
  - Proximity
  - Similarity
  - Familiarity
  - Self-disclosure

  Employees should be encouraged to invite family
  members to events; employees enjoy being able to show off their work
  place to their families. Also, instead of awkward social
  get-togethers, consider having events with a common goal that people
  work towards.

  If you are having constant conflicts with a colleague, find common
  goals that you can both strive towards. Gossip is a powerful tool in
  human communications but be careful about encouraging it too much.


* Lessons of autonomy

  Let the team steer its own path. Your job is to ask questions and
  provide feedback.

  Human beings generally appreciate higher autonomy more than higher
  income in a new job.

  In addition to autonomy, human beings need to increase their
  competence through increasing challenges and need to see the meaning
  of what they are doing.

  For established companies, make sure that employees understand the
  history of the company. For new companies, make sure that employees
  have reason to be passionate about the work of the company. This can
  lead to employees being more engaged. Also, let employees be seen as
  publicly owning their work. This is better than reinforcing
  anonymity.


* Lessons of listening

  Increase your listening-to-talking ratio and your
  questions-to-answers ratio. You do not progress in your career by
  winning arguments; you progress by finding common ground.

  Find a PEARLS (Partnership, Empathy, Acknowledgement, Respect, Legitimacy,
  Support) item to add in every workplace conversation.

  Clear the relationship channel first when you have issues in the
  task channel. For instance, if you are having a heated conversation
  over a tactical issue, let your colleague know that you respect
  their overall capability.
