#+Title: List of books to read
#+FILETAGS: :Books:
#+STARTUP: content

* Books analysis


** Usual process to use this tool

   - Check the next 3 textbooks to read
   - Pick the next 3 non-textbooks to read from the list of 20 below
   - Put holds in Libby for any of the 6 above that are available
   - Have at least one textbook and one non-textbook to read at all times


** TODO Add an option in recommend_book.py to exclude a genre (e.g. -xg textbook) :Software:
   :PROPERTIES:
   :EFFORT:  00:15
   :BENEFIT: 10
   :RATIO: 0.40
   :END:


** TODO Allow multiple genres in recommend_book.py (e.g. -g"textbook,management") :Software:
   :PROPERTIES:
   :EFFORT:  00:15
   :BENEFIT: 10
   :RATIO: 0.40
   :END:


** TODO Add an option in recommend_book.py to list by status (e.g. -s reading) :Software:
   :PROPERTIES:
   :EFFORT:  00:15
   :BENEFIT: 10
   :RATIO: 0.40
   :END:



** Next few books to read overall

#+begin_src shell :results output :wrap "EXPORT html" :exports both
../item_recommender/recommend_book.py -r 20 books_list.csv
#+end_src

#+RESULTS:
#+begin_EXPORT html
List of recommended books:

Crossing Point                                    : James Glickman       (4.3, fiction)
Jesus' Son                                        : Denis Johnson        (4.1, fiction)
Storytelling with data                            : Cole Nussbaumer...   (4.3, design)
Marketing Management                              : Philip Kotler        (4.1, marketing,management,textbook)
Compulsion                                        : Meyer Levin          (4.1, thriller)
Nimitz at war                                     : Craig Symonds        (4.4, western-history)
Five Families: The Rise,Decline,and Resurgence... : Selwyn Raab          (4.1, western-biography)
The Christmas Virtues: A Treasury of...           : Jonathan V. Last     (4.1, society)
The whys of a political scrivener                 : Martin Gardner       (4.0, philosophy)
Amos Walker: The Complete Story Collection        : Loren D. Estleman    (4.1, thriller)
Say Nothing                                       : Patrick Keefe        (4.4, western-history)
Spearhead                                         : Adam Makos           (4.2, western-history)
A different drummer                               : William Melvin...    (4.2, fiction)
Economic Hierarchies,Organization and the...      : Gordon Tullock       (4.0, economics,textbook)
A cartoon history of the universe                 : Larry Gonick         (4.3, eastern-history,western-history)
The Man Who Mistook His Wife for a Hat and...     : Oliver Sacks         (4.1, brain)
The Logic of Collective Action: Public Goods...   : Mancur Olson         (4.0, society,textbook)
The Makioka Sisters                               : Junichiro Tanizaki   (4.0, japanese-fiction)
A World Undone: A History of World War I          : G J Meyer            (4.2, western-history)
The Scramble for Africa: The White Man's...       : Thomas Pakenham      (4.1, eastern-history)
#+end_EXPORT


** Next textbook to read

#+begin_src shell :results drawer :exports both
../item_recommender/recommend_book.py -r 5 -g textbook books_list.csv
#+end_src

#+RESULTS:
:results:
List of recommended books:

Marketing Management                              : Philip Kotler        (4.1, marketing,management,textbook)
Economic Hierarchies,Organization and the...      : Gordon Tullock       (4.0, economics,textbook)
The Logic of Collective Action: Public Goods...   : Mancur Olson         (4.0, society,textbook)
Strategic Management                              : Charles Hill,...     (4.5, strategy,management,textbook,books-to-read-again)
Bayesian data analysis                            : Andrew Gelman        (4.2, maths,textbook)
:end:


** Books that I have read before but should read again

#+begin_src shell :results drawer :exports both
../item_recommender/recommend_book.py -r 10 -g books-to-read-again books_list.csv
#+end_src

#+RESULTS:
:results:
List of recommended books:

The life you can save                             : Peter Singer         (4.5, philosophy,books-to-read-again)
Strategic Management                              : Charles Hill,...     (4.5, strategy,management,textbook,books-to-read-again)
Culture map                                       : Erin Meyer           (4.4, management,books-to-read-again)
The Pragmatic Programmer: From Journeyman to...   : Andy Hunt            (4.3, software,books-to-read-again)
Models of the mind                                : Grace Lindsay        (4.4, brain,books-to-read-again)
Working backwards                                 : Colin Bryar, Bill... (4.4, management,books-to-read-again)
Imperial twilight: the opium war                  : Stephen Platt        (4.3, eastern-history,books-to-read-again)
The Effective Executive: The Definitive Guide...  : Peter F. Drucker     (4.1, management,books-to-read-again)
Free to Choose: A Personal Statement              : Milton Friedman      (4.2, economics,books-to-read-again)
The War That Ended Peace: The Road to 1914        : Margaret MacMillan   (4.2, western-history,books-to-read-again)
:end:


** Recently read

#+begin_src shell :results drawer :exports both
../item_recommender/recommend_book.py -s 50 books_list.csv
#+end_src

#+RESULTS:
:results:
List of read books:

The Grid                                          : Philip Schewe        (11-Nov-24, 4.0)
Magdalena: River of dreams                        : Wade Davis           (26-Oct-24, 2.0)
Only the paranoid survive                         : Andrew Grove         (26-Oct-24, 2.0)
Becoming Trader Joe                               : Joe Coulombe         (14-Oct-24, 5.0)
The law of innocence                              : Michael Connelly     (25-Aug-24, 5.0)
The shadow district                               : Arnaldur Indridason  (20-Aug-24, 4.0)
Life on a young planet: the first 3 billion years : Andrew Knoll         (20-Aug-24, 1.0)
Life 3.0: Being Human in the Age of Artificial... : Max Tegmark          (02-Aug-24, 1.0)
The Florentines                                   : Paul Strathern       (02-Aug-24, 5.0)
The vital question: Energy, evolution and the...  : Nick Lane            (01-Aug-24, 1.0)
Shape                                             : Jordan Ellenberg     (20-Jul-24, 5.0)
Scaling people                                    : Claire Hughes...     (05-Jul-24, 3.0)
The missing billionaires                          : Victor Haghani       (20-Jun-24, 4.0)
The silk roads                                    : Peter Frankopan      (12-Jun-24, 2.0)
Trillion dollar coach                             : Eric Schmidt,...     (05-Jun-24, 4.0)
High output management                            : Andrew Grove         (30-May-24, 5.0)
Measure what matters                              : John Doerr           (10-Apr-24, 4.0)
The rebellious life of Mrs. Rosa Parks            : Jeanne Theoharis     (10-Jan-24, 5.0)
How the world really works                        : Vaclav Smil          (01-Jan-24, 5.0)
An honorable man                                  : Paul Vidich          (15-Dec-23, 4.0)
The Art of Action                                 : Stephen Bungay       (01-Dec-23, 2.0)
Ponniyil Selvan - book 1                          : Kalki                (20-Jul-23, 5.0)
The diamond eye                                   : Kate Quinn           (05-Jul-23, 3.0)
A failed empire                                   : Vladislav Zubok      (15-Feb-23, 3.0)
Lenin the dictator                                : Victor Sebestyen     (25-Nov-22, 5.0)
Nuclear Folly                                     : Serhii Plokhy        (04-Oct-22, 5.0)
Who gets what and why                             : Alvin Roth           (15-Sep-22, 3.0)
These women                                       : Ivy Pochoda          (25-Jul-22, 5.0)
The Elephant in the Brain                         : Kevin Simler         (18-Jul-22, 5.0)
The Best Place to Work: The Art and Science of... : Ron Friedman         (07-Jul-22, 5.0)
Tumbling                                          : Diane McKinney-...   (15-Apr-22, 4.0)
Infectious: Pathogens and how we fight them       : John Tregoning       (10-Apr-22, 1.0)
Confessions                                       : Kanae Minato         (21-Feb-22, 4.0)
Sync: the emerging science of social order        : Steven Strogatz      (27-Jan-22, 2.0)
The dead are arising: The life of Malcolm X       : Les Payne            (24-Jan-22, 4.0)
Designing data-intensive applications             : Martin Kleppmann     (15-Jan-22, 5.0)
Alan Turing: The Enigma                           : Andrew Hodges        (12-Jan-22, 4.0)
Fundamentals                                      : Frank Wilczek        (25-Dec-21, 1.0)
Leaving Berlin                                    : Joseph Kanon         (18-Dec-21, 4.0)
The Transformation of the World: A Global...      : Jurgen Osterhammel   (18-Dec-21, 2.0)
Shuggie Bain                                      : Douglas Stuart       (07-Dec-21, 3.0)
Seiobo There Below                                : Laszlo Krasznahorkai (30-Nov-21, 1.0)
Many thousands gone: A history of slavery         : Ira Berlin           (26-Nov-21, 5.0)
The burning room                                  : Michael Connelly     (22-Nov-21, 4.0)
I contain multitudes: the microbes within us      : Ed Yong              (12-Nov-21, 2.0)
The spy and the traitor                           : Ben MacIntyre        (30-Sep-21, 5.0)
Osman's dream: A history of the Ottoman Empire    : Carolin Finkel       (22-Sep-21, 2.0)
Transcendent kingdom                              : Yaa Gyasi            (08-Sep-21, 3.0)
Why Meditate?: Working with Thoughts and Emotions : Matthieu Ricard      (25-Aug-21, 3.0)
Climate Change: What everyone needs to know       : Joseph Romm          (20-Aug-21, 4.0)
:end:



** List of genres

#+begin_src shell :results drawer :exports both
  ../item_recommender/recommend_book.py -l books_list.csv
#+end_src

#+RESULTS:
:results:
List of categories and read-dates:
maths                         : 04-Aug-24
brain                         : 04-Aug-24
philosophy                    : 04-Aug-24
biology                       : 04-Aug-24
textbook                      : 04-Aug-24
western-biography             : 02-Aug-24
management                    : 25-Jul-24
books-to-read-again           : 25-Jul-24
finance                       : 20-Jun-24
eastern-history               : 12-Jun-24
black-biography               : 12-Jan-24
science                       : 01-Jan-24
espionage                     : 15-Dec-23
indian-fiction                : 20-Jul-23
thriller                      : 05-Jul-23
western-history               : 04-Oct-22
economics                     : 15-Sep-22
games                         : 15-Sep-22
fiction                       : 15-Apr-22
strategy                      : 22-Mar-22
software                      : 15-Jan-22
engineering                   : 15-Jan-22
physics                       : 25-Dec-21
black-history                 : 26-Nov-21
eastern-biography             : 30-Sep-21
buddhism                      : 25-Aug-21
society                       : 26-Jun-21
indian-society                : 12-Jan-21
science-fiction               : 05-Jan-21
african-fiction               : 11-Dec-20
scandinavian-thriller         : 25-Nov-20
black-fiction                 : 11-Oct-20
self-improvement              : 07-Aug-20
poetry                        : 23-Jun-20
eastern-fiction               : 07-Feb-20
genetics                      : 02-Jan-20
sports                        : 02-Jan-20
product                       : 01-Dec-19
process                       : 06-Jul-19
indian-history                : 28-Aug-18
kids                          : 30-Nov-17
japanese-fiction              : 02-Jul-17
design                        : 05-May-15
marketing                     : 01-Jan-00
:end:


** Favorite authors

#+begin_src shell :results drawer :exports both
  ../item_recommender/recommend_book.py -a 30 books_list.csv
#+end_src

#+RESULTS:
:results:
List of best authors:

Peter Singer
John Darwin
Anthony Marra
Patricia Highsmith
P. G. Wodehouse
Michael Korda
Jonathan Haidt
Mira Jacob
David Ignatius
Tania James
J.K. Rowling
Charles Cumming
Alexander Soderberg
John Sandford
David Downing
Jeffrey Archer
Amitav Ghosh
John Steinbeck
Russell Banks
Joseph Kanon
David McCullough
Richard Russo
Yaa Gyasi
Anthony Horowitz
Linwood Barclay
Tom DeMarco
Graham Greene
Kiran Nagarkar
Jhumpa Lahiri
Shyam Selvadurai
:end:


** Books to read by genre

#+begin_src shell :results drawer :exports both
  ../item_recommender/recommend_book.py -g maths -r 20 books_list.csv
#+end_src

#+RESULTS:
:results:
List of recommended books:

Bayesian data analysis                            : Andrew Gelman        (4.2, maths,textbook)
Statistics as principled argument                 : Robert Abelson       (4.1, maths)
Games of life                                     : Karl Sigmund         (4.0, maths)
Algorithms to Live By: The Computer Science of... : Brian Christian      (4.2, maths,books-to-read-again)
Investment under uncertainty                      : Avinash Dixit,...    (4.0, maths)
Game theory: an introduction                      : Steve Tadelis        (4.0, maths,textbook,books-to-read-again)
Bubble or revolution?                             : Neel Mehta           (4.0, finance,maths,books-to-read-again)
An introduction to decision theory                : Martin Peterson      (3.8, maths,textbook,books-to-read-again)
:end:


** Options

#+begin_src shell :results drawer :exports both
  ../item_recommender/recommend_book.py -h
#+end_src

#+RESULTS:
:results:
usage: recommend_book.py [-h] [-l] [-s NUM_READ_BOOKS]
                         [-r NUM_RECOMMEND_BOOKS] [-a NUM_AUTHORS] [-g GENRE]
                         [-ra AUTHOR]
                         books_file

Search for and recommend books using books_file. By default, show the 20 best
books to read next.

positional arguments:
  books_file

options:
  -h, --help            show this help message and exit
  -l, --list_genres
  -s NUM_READ_BOOKS, --list_read_books NUM_READ_BOOKS
  -r NUM_RECOMMEND_BOOKS, --recommend_books NUM_RECOMMEND_BOOKS
  -a NUM_AUTHORS, --list_best_authors NUM_AUTHORS
  -g GENRE, --restrict_by_genre GENRE
  -ra AUTHOR, --restrict_by_author AUTHOR
:end:


* Sources for book recommendations

  - [[https://www.goodreads.com/list][Goodreads lists]]
  - [[https://en.wikipedia.org/wiki/List_of_winners_and_shortlisted_authors_of_the_Booker_Prize][Booker prize winners]]
  - [[https://en.wikipedia.org/wiki/Royal_Society_Prizes_for_Science_Books][Royal Society awards]] for science books
  - [[https://www.thehugoawards.org/hugo-history/][Hugo prize]] for science fiction
  - [[https://en.wikipedia.org/wiki/James_Tait_Black_Memorial_Prize#List_of_recipients][James Tait Black prize]] for biography

  - [[https://en.wikipedia.org/wiki/DSC_Prize_for_South_Asian_Literature][DSC prize for South Asian literature]]
  - [[https://www.thejcbprize.org/#list][JCB prize for Indian fiction]]
  - [[https://en.wikipedia.org/wiki/Crossword_Book_Award][Crossword award for Indian literature]]
