#+Title: List of books to read
#+FILETAGS: :Books:
#+STARTUP: content

* Books analysis


** Usual process to use this tool

   - Check the next 3 textbooks to read
   - Pick the next 3 non-textbooks to read from the list of 20 below
   - Put holds in Libby for any of the 6 above that are available
   - Have at least one textbook and one non-textbook to read at all times


** TODO Add an option in recommend_book.py to exclude a genre (e.g. -xg textbook)
   :PROPERTIES:
   :EFFORT:  00:15
   :BENEFIT: 10
   :RATIO: 0.40
   :END:


** TODO Allow multiple genres in recommend_book.py (e.g. -g"textbook,management")
   :PROPERTIES:
   :EFFORT:  00:15
   :BENEFIT: 10
   :RATIO: 0.40
   :END:


** TODO Add an option in recommend_book.py to list by status (e.g. -s reading)
   :PROPERTIES:
   :EFFORT:  00:15
   :BENEFIT: 10
   :RATIO: 0.40
   :END:



** Next few books to read overall

#+begin_src shell :results drawer
../item_recommender/recommend_book.py -r 20 books_list.csv
#+end_src

#+RESULTS:
:results:
List of recommended books:

Crossing Point                                    : James Glickman       (4.3, fiction)
Magdalena: River of dreams                        : Wade Davis           (4.4, society)
Jesus' Son                                        : Denis Johnson        (4.1, fiction)
Storytelling with data                            : Cole Nussbaumer...   (4.3, design)
Nimitz at war                                     : Craig Symonds        (4.4, western-history)
Marketing Management                              : Philip Kotler        (4.1, marketing,management,textbook)
Compulsion                                        : Meyer Levin          (4.1, thriller)
The Christmas Virtues: A Treasury of...           : Jonathan V. Last     (4.1, society)
The whys of a political scrivener                 : Martin Gardner       (4.0, philosophy)
Say Nothing                                       : Patrick Keefe        (4.4, western-history)
Five Families: The Rise,Decline,and Resurgence... : Selwyn Raab          (4.1, western-biography)
Amos Walker: The Complete Story Collection        : Loren D. Estleman    (4.1, thriller)
Spearhead                                         : Adam Makos           (4.2, western-history)
A different drummer                               : William Melvin...    (4.2, fiction)
A cartoon history of the universe                 : Larry Gonick         (4.3, eastern-history,western-history)
Economic Hierarchies,Organization and the...      : Gordon Tullock       (4.0, economics)
Fundamentals of software architecture             : Mark Richards,...    (4.3, software,engineering,textbook)
The Logic of Collective Action: Public Goods...   : Mancur Olson         (4.0, society)
Life 3.0: Being Human in the Age of Artificial... : Max Tegmark          (4.1, brain)
The Man Who Mistook His Wife for a Hat and...     : Oliver Sacks         (4.1, science)
:end:


** Next textbook to read

#+begin_src shell :results drawer
../item_recommender/recommend_book.py -r 3 -g textbook books_list.csv
#+end_src

#+RESULTS:
:results:
List of recommended books:

Marketing Management                              : Philip Kotler        (4.1, marketing,management,textbook)
Fundamentals of software architecture             : Mark Richards,...    (4.3, software,engineering,textbook)
Bayesian data analysis                            : Andrew Gelman        (4.2, maths,textbook)
:end:


** Books that I have read before but should read again

#+begin_src shell :results drawer
../item_recommender/recommend_book.py -r 5 -g books-to-read-again books_list.csv
#+end_src

#+RESULTS:
:results:
List of recommended books:

A Fine Balance                                    : Rohinton Mistry      (4.4, indian-fiction,books-to-read-again)
Good Strategy Bad Strategy: The Difference and... : Richard P. Rumelt    (4.2, strategy,management,books-to-read-again)
Free to Choose: A Personal Statement              : Milton Friedman      (4.2, economics,books-to-read-again)
The Effective Executive: The Definitive Guide...  : Peter F. Drucker     (4.1, management,books-to-read-again)
The Essential Deming: Leadership Principles...    : W. Edwards Deming    (4.1, management,books-to-read-again)
:end:


** Recently read

#+begin_src shell :results drawer
../item_recommender/recommend_book.py -s 50 books_list.csv
#+end_src

#+RESULTS:
:results:
List of read books:

The silk roads                                    : Peter Frankopan      (12-Jun-24, 2.0)
Trillion dollar coach                             : Eric Schmidt,...     (05-Jun-24, 4.0)
High output management                            : Andrew Grove         (30-May-24, 5.0)
Measure what matters                              : John Doerr           (10-Apr-24, 4.0)
Bubble or revolution?                             : Neel Mehta           (30-Mar-24, 5.0)
Working backwards                                 : Colin Bryar, Bill... (01-Feb-24, 5.0)
King                                              : Jonathan Eig         (12-Jan-24, 5.0)
The rebellious life of Mrs. Rosa Parks            : Jeanne Theoharis     (10-Jan-24, 5.0)
Business model generation                         : Alex Osterwalder     (01-Jan-24, 5.0)
How the world really works                        : Vaclav Smil          (01-Jan-24, 5.0)
An honorable man                                  : Paul Vidich          (15-Dec-23, 4.0)
The Art of Action                                 : Stephen Bungay       (01-Dec-23, 2.0)
Ponniyil Selvan - book 1                          : Kalki                (20-Jul-23, 5.0)
The diamond eye                                   : Kate Quinn           (05-Jul-23, 3.0)
The big picture                                   : Sean B. Carroll      (01-Jul-23, 5.0)
Models of the mind                                : Grace Lindsay        (01-Jun-23, 5.0)
A failed empire                                   : Vladislav Zubok      (15-Feb-23, 3.0)
Lenin the dictator                                : Victor Sebestyen     (25-Nov-22, 5.0)
Nuclear Folly                                     : Serhii Plokhy        (04-Oct-22, 5.0)
Who gets what and why                             : Alvin Roth           (15-Sep-22, 3.0)
Culture map                                       : Erin Meyer           (05-Sep-22, 5.0)
These women                                       : Ivy Pochoda          (25-Jul-22, 5.0)
The Elephant in the Brain                         : Kevin Simler         (18-Jul-22, 5.0)
The Best Place to Work: The Art and Science of... : Ron Friedman         (07-Jul-22, 5.0)
Tumbling                                          : Diane McKinney-...   (15-Apr-22, 4.0)
Infectious: Pathogens and how we fight them       : John Tregoning       (10-Apr-22, 1.0)
Strategic Management                              : Charles Hill,...     (22-Mar-22, 5.0)
Confessions                                       : Kanae Minato         (21-Feb-22, 4.0)
Your inner fish                                   : Neil Shubin          (12-Feb-22, 5.0)
Sync: the emerging science of social order        : Steven Strogatz      (27-Jan-22, 2.0)
The dead are arising: The life of Malcolm X       : Les Payne            (24-Jan-22, 4.0)
Designing data-intensive applications             : Martin Kleppmann     (15-Jan-22, 5.0)
Alan Turing: The Enigma                           : Andrew Hodges        (12-Jan-22, 4.0)
Fundamentals                                      : Frank Wilczek        (25-Dec-21, 1.0)
Leaving Berlin                                    : Joseph Kanon         (18-Dec-21, 4.0)
The Transformation of the World: A Global...      : Jurgen Osterhammel   (18-Dec-21, 2.0)
Shuggie Bain                                      : Douglas Stuart       (07-Dec-21, 3.0)
Seiobo There Below                                : Laszlo Krasznahorkai (30-Nov-21, 1.0)
Many thousands gone: A history of slavery         : Ira Berlin           (26-Nov-21, 5.0)
The burning room                                  : Michael Connelly     (22-Nov-21, 4.0)
Game theory: an introduction                      : Steve Tadelis        (20-Nov-21, 5.0)
I contain multitudes: the microbes within us      : Ed Yong              (12-Nov-21, 2.0)
Algorithms to Live By: The Computer Science of... : Brian Christian      (10-Oct-21, 5.0)
The spy and the traitor                           : Ben MacIntyre        (30-Sep-21, 5.0)
Osman's dream: A history of the Ottoman Empire    : Carolin Finkel       (22-Sep-21, 2.0)
Transcendent kingdom                              : Yaa Gyasi            (08-Sep-21, 3.0)
Why Meditate?: Working with Thoughts and Emotions : Matthieu Ricard      (25-Aug-21, 3.0)
Climate Change: What everyone needs to know       : Joseph Romm          (20-Aug-21, 4.0)
False Alarm                                       : Bjorn Lomborg        (10-Aug-21, 5.0)
The Happiness Hypothesis                          : Jonathan Haidt       (25-Jul-21, 4.0)
:end:



** List of genres

#+begin_src shell :results drawer
  ../item_recommender/recommend_book.py -l books_list.csv
#+end_src

#+RESULTS:
:results:
List of categories and read-dates:
maths                         : 12-Jun-24
eastern-history               : 12-Jun-24
textbook                      : 12-Jun-24
western-biography             : 12-Jun-24
finance                       : 12-Jun-24
management                    : 05-Jun-24
black-biography               : 12-Jan-24
science                       : 01-Jan-24
espionage                     : 15-Dec-23
books-to-read-again           : 01-Nov-23
indian-fiction                : 20-Jul-23
thriller                      : 05-Jul-23
biology                       : 01-Jul-23
brain                         : 01-Jun-23
western-history               : 04-Oct-22
economics                     : 15-Sep-22
games                         : 15-Sep-22
fiction                       : 15-Apr-22
strategy                      : 22-Mar-22
software                      : 15-Jan-22
engineering                   : 15-Jan-22
physics                       : 25-Dec-21
black-history                 : 26-Nov-21
eastern-biography             : 30-Sep-21
buddhism                      : 25-Aug-21
philosophy                    : 25-Jul-21
society                       : 26-Jun-21
indian-society                : 12-Jan-21
science-fiction               : 05-Jan-21
african-fiction               : 11-Dec-20
scandinavian-thriller         : 25-Nov-20
black-fiction                 : 11-Oct-20
self-improvement              : 07-Aug-20
poetry                        : 23-Jun-20
eastern-fiction               : 07-Feb-20
genetics                      : 02-Jan-20
sports                        : 02-Jan-20
product                       : 01-Dec-19
process                       : 06-Jul-19
indian-history                : 28-Aug-18
kids                          : 30-Nov-17
japanese-fiction              : 02-Jul-17
design                        : 05-May-15
marketing                     : 01-Jan-00
:end:


** Favorite authors

#+begin_src shell :results drawer
  ../item_recommender/recommend_book.py -a 30 books_list.csv
#+end_src

#+RESULTS:
:results:
List of best authors:

Peter Singer
John Darwin
Anthony Marra
Patricia Highsmith
P. G. Wodehouse
Michael Korda
Jonathan Haidt
Mira Jacob
David Ignatius
Tania James
J.K. Rowling
Charles Cumming
Alexander Soderberg
John Sandford
David Downing
Jeffrey Archer
Amitav Ghosh
John Steinbeck
Russell Banks
Joseph Kanon
David McCullough
Richard Russo
Yaa Gyasi
Anthony Horowitz
Linwood Barclay
Tom DeMarco
Graham Greene
Kiran Nagarkar
Jhumpa Lahiri
Shyam Selvadurai
:end:


** Books to read by genre

#+begin_src shell :results drawer
  ../item_recommender/recommend_book.py -g management books_list.csv
#+end_src

#+RESULTS:
:results:
List of recommended books:

Marketing Management                              : Philip Kotler        (4.1, marketing,management,textbook)
Scaling people                                    : Claire Hughes...     (4.4, management)
Reading the room                                  : David Kantor         (4.2, management)
This Is Marketing: You Can't Be Seen Until You... : Seth Godin           (4.1, marketing,management)
Management 3.0: Leading Agile...                  : Jurgen Appelo        (4.1, process,management)
Good Strategy Bad Strategy: The Difference and... : Richard P. Rumelt    (4.2, strategy,management,books-to-read-again)
The Effective Executive: The Definitive Guide...  : Peter F. Drucker     (4.1, management,books-to-read-again)
Sensemaking in organizations                      : Karl Weick           (4.0, management)
Questions are the answer                          : Hal Gregersen        (4.0, management)
Judgement in managerial decision making           : Bazerman, Moore      (4.0, management)
Strategy: A history                               : Lawrence Freedman    (4.0, strategy,management)
Build: An unorthodox guide to making things       : Tony Fadell          (4.0, management,product)
The Essential Deming: Leadership Principles...    : W. Edwards Deming    (4.1, management,books-to-read-again)
How big things get done                           : Bent Flyvbjerg       (4.0, management)
The culture engine                                : Chris Edmonds        (4.0, management)
Crossing the Chasm: Marketing and Selling High-...: Geoffrey A. Moore    (4.0, management,books-to-read-again)
The first 90 days                                 : Michael Watkins      (3.9, management)
How to Measure Anything: Finding the Value of...  : Douglas W. Hubbard   (4.0, management,books-to-read-again)
Thinking Strategically: The Competitive Edge in...: Avinash K. Dixit     (4.0, strategy,management,books-to-read-again)
The Halo Effect: ... and the Eight Other...       : Philip M. Rosenzweig (3.9, management,books-to-read-again)
:end:


** Options

#+begin_src shell :results drawer
  ../item_recommender/recommend_book.py -h
#+end_src

#+RESULTS:
:results:
usage: recommend_book.py [-h] [-l] [-s NUM_READ_BOOKS]
                         [-r NUM_RECOMMEND_BOOKS] [-a NUM_AUTHORS] [-g GENRE]
                         [-ra AUTHOR]
                         books_file

Search for and recommend books using books_file. By default, show the 20 best
books to read next.

positional arguments:
  books_file

options:
  -h, --help            show this help message and exit
  -l, --list_genres
  -s NUM_READ_BOOKS, --list_read_books NUM_READ_BOOKS
  -r NUM_RECOMMEND_BOOKS, --recommend_books NUM_RECOMMEND_BOOKS
  -a NUM_AUTHORS, --list_best_authors NUM_AUTHORS
  -g GENRE, --restrict_by_genre GENRE
  -ra AUTHOR, --restrict_by_author AUTHOR
:end:


* Sources for book recommendations

  - [[https://www.goodreads.com/list][Goodreads lists]]
  - [[https://en.wikipedia.org/wiki/List_of_winners_and_shortlisted_authors_of_the_Booker_Prize][Booker prize winners]]
  - [[https://en.wikipedia.org/wiki/Royal_Society_Prizes_for_Science_Books][Royal Society awards]] for science books
  - [[https://www.thehugoawards.org/hugo-history/][Hugo prize]] for science fiction

  - [[https://en.wikipedia.org/wiki/DSC_Prize_for_South_Asian_Literature][DSC prize for South Asian literature]]
  - [[https://www.thejcbprize.org/#list][JCB prize for Indian fiction]]
  - [[https://en.wikipedia.org/wiki/Crossword_Book_Award][Crossword award for Indian literature]]
