#+Title: List of books to read
#+FILETAGS: :Books:
#+STARTUP: content

* Books analysis


** Usual process to use this tool

   - Check the next 3 textbooks to read
   - Pick the next 3 non-textbooks to read from the list of 20 below
   - Have at least one textbook and one non-textbook to read at all times


** Next few books to read overall

#+begin_src shell :results drawer :exports both
../item_recommender/recommend_book.py -r 10 books_list.csv
#+end_src

#+RESULTS:
:results:
List of recommended books:

The Makioka Sisters                               : Junichiro Tanizaki   (4.0, japanese-fiction)
Storytelling with data                            : Cole Nussbaumer...   (4.3, design,textbook)
Tasting freedom: Octavius Catto                   : Daniel Biddle,...    (4.2, black-biography)
Say Nothing                                       : Patrick Keefe        (4.4, western-history)
Oryx and Crake                                    : Margaret Atwood      (4.0, science-fiction)
A different drummer                               : William Melvin...    (4.2, fiction)
Anatomy of a Miracle: The End of Apartheid        : Patti Waldmeir       (4.1, eastern-history)
This Is Marketing: You Can't Be Seen Until You... : Seth Godin           (4.1, marketing,management)
Ivan's War: Life and Death in the Red...          : Catherine Merridale  (4.0, eastern-history)
Thus Bad Begins                                   : Javier Marias        (4.0, thriller)
:end:

** Next textbook to read

#+begin_src shell :results drawer :exports both
../item_recommender/recommend_book.py -r 20 -g textbook books_list.csv
#+end_src

#+RESULTS:
:results:
List of recommended books:

Artificial intelligence: A modern approach        : Stuart Russell,...   (4.2, science,textbook)
Designing data-intensive applications             : Martin Kleppmann     (4.5, software,engineering,textbook,books-to-read-again)
Strategic Management                              : Charles Hill,...     (4.5, strategy,management,textbook,books-to-read-again)
Automotive technology: a systems approach         : Jack Erjavec         (4.0, engineering,textbook)
Knowledge,reality and value                       : Michael Huemer       (4.1, philosophy,textbook,books-to-read-again)
Game theory: an introduction                      : Steve Tadelis        (4.0, maths,textbook,books-to-read-again)
The missing billionaires                          : Victor Haghani       (4.0, maths,finance,textbook,books-to-read-again)
An introduction to decision theory                : Martin Peterson      (3.8, maths,textbook,books-to-read-again)
:end:

** Books that I have read before but should read again

#+begin_src shell :results drawer :exports both
../item_recommender/recommend_book.py -r 10 -g books-to-read-again books_list.csv
#+end_src

#+RESULTS:
:results:
List of recommended books:

The life you can save                             : Peter Singer         (4.5, philosophy,books-to-read-again)
Designing data-intensive applications             : Martin Kleppmann     (4.5, software,engineering,textbook,books-to-read-again)
Strategic Management                              : Charles Hill,...     (4.5, strategy,management,textbook,books-to-read-again)
Culture map                                       : Erin Meyer           (4.4, management,books-to-read-again)
Working backwards                                 : Colin Bryar, Bill... (4.4, management,books-to-read-again)
The Pragmatic Programmer: From Journeyman to...   : Andy Hunt            (4.3, software,books-to-read-again)
Models of the mind                                : Grace Lindsay        (4.4, brain,books-to-read-again)
Imperial twilight: the opium war                  : Stephen Platt        (4.3, eastern-history,books-to-read-again)
The Effective Executive: The Definitive Guide...  : Peter F. Drucker     (4.1, management,books-to-read-again)
Free to Choose: A Personal Statement              : Milton Friedman      (4.2, economics,books-to-read-again)
:end:

** Recently read

#+begin_src shell :results drawer :exports both
../item_recommender/recommend_book.py -s 50 books_list.csv
#+end_src

#+RESULTS:
:results:
List of read books:

An officer and a spy                              : Robert Harris        (31-Dec-25, 5.0)
The Intel trinity                                 : Michael S. Malone    (25-Dec-25, 5.0)
Thinking in bets                                  : Annie Duke           (09-Nov-25, 3.0)
Master of precision: Henry Leland                 : Ottilie Leland,...   (05-Nov-25, 5.0)
From the American System to Mass Production       : David Hounshell      (01-Nov-25, 5.0)
Enlightenment now                                 : Steven Pinker        (17-Oct-25, 5.0)
Freshwater                                        : Akwaeke Emezi        (01-Sep-25, 1.0)
Pragmatic thinking and learning                   : Andy Hunt            (01-Sep-25, 5.0)
Chrysler: The Life and Times of an Automotive...  : Vincent Curcio       (01-Sep-25, 5.0)
Nimitz at war                                     : Craig Symonds        (30-Jul-25, 5.0)
Statistics as principled argument                 : Robert Abelson       (01-Jul-25, 1.0)
Henry Ford                                        : Vincent Curcio       (21-Jun-25, 5.0)
Stone mattress                                    : Margaret Atwood      (10-Jun-25, 5.0)
Sloan rules                                       : Henry Farber         (20-May-25, 5.0)
The sleep prescription                            : Arik Prather         (13-Apr-25, 5.0)
The gatekeepers                                   : Chris Whipple        (13-Apr-25, 5.0)
King Richard                                      : Michael Dobbs        (13-Apr-25, 5.0)
Secure software systems                           : Erik Fretheim        (05-Jan-25, 2.0)
Amos Walker: The Complete Story Collection        : Loren D. Estleman    (04-Jan-25, 1.0)
Talking to the enemy: faith, brotherhood,and...   : Scott Atran          (14-Dec-24, 1.0)
A cartoon history of the universe                 : Larry Gonick         (14-Dec-24, 2.0)
Crossing Point                                    : James Glickman       (01-Dec-24, 4.0)
Magdalena: River of dreams                        : Wade Davis           (26-Oct-24, 2.0)
Only the paranoid survive                         : Andrew Grove         (26-Oct-24, 2.0)
Becoming Trader Joe                               : Joe Coulombe         (14-Oct-24, 5.0)
The law of innocence                              : Michael Connelly     (25-Aug-24, 5.0)
The shadow district                               : Arnaldur Indridasson (20-Aug-24, 4.0)
Life on a young planet: the first 3 billion years : Andrew Knoll         (20-Aug-24, 1.0)
Life 3.0: Being Human in the Age of Artificial... : Max Tegmark          (02-Aug-24, 1.0)
The Florentines                                   : Paul Strathern       (02-Aug-24, 5.0)
The vital question: Energy, evolution and the...  : Nick Lane            (01-Aug-24, 1.0)
Shape                                             : Jordan Ellenberg     (20-Jul-24, 5.0)
Scaling people                                    : Claire Hughes...     (05-Jul-24, 3.0)
The silk roads                                    : Peter Frankopan      (12-Jun-24, 2.0)
Trillion dollar coach                             : Eric Schmidt,...     (05-Jun-24, 4.0)
High output management                            : Andrew Grove         (30-May-24, 5.0)
Measure what matters                              : John Doerr           (10-Apr-24, 4.0)
The rebellious life of Mrs. Rosa Parks            : Jeanne Theoharis     (10-Jan-24, 5.0)
How the world really works                        : Vaclav Smil          (01-Jan-24, 5.0)
An honorable man                                  : Paul Vidich          (15-Dec-23, 4.0)
The Art of Action                                 : Stephen Bungay       (01-Dec-23, 2.0)
Ponniyil Selvan - book 1                          : Kalki                (20-Jul-23, 5.0)
The diamond eye                                   : Kate Quinn           (05-Jul-23, 3.0)
A failed empire                                   : Vladislav Zubok      (15-Feb-23, 3.0)
Lenin the dictator                                : Victor Sebestyen     (25-Nov-22, 5.0)
Nuclear Folly                                     : Serhii Plokhy        (04-Oct-22, 5.0)
Who gets what and why                             : Alvin Roth           (15-Sep-22, 3.0)
These women                                       : Ivy Pochoda          (25-Jul-22, 5.0)
The Elephant in the Brain                         : Kevin Simler         (18-Jul-22, 5.0)
The Best Place to Work: The Art and Science of... : Ron Friedman         (07-Jul-22, 5.0)
:end:



** List of genres

#+begin_src shell :results drawer :exports both
  ../item_recommender/recommend_book.py -l books_list.csv
#+end_src

#+RESULTS:
:results:
List of categories and read-dates:
engineering                   : 01-Sep-25
western-biography             : 01-Sep-25
brain                         : 01-Sep-25
textbook                      : 01-Sep-25
western-history               : 01-Sep-25
software                      : 01-Sep-25
western-fiction               : 10-Jun-25
science                       : 13-Apr-25
thriller                      : 04-Jan-25
society                       : 14-Dec-24
eastern-history               : 14-Dec-24
fiction                       : 01-Dec-24
books-to-read-again           : 11-Nov-24
management                    : 26-Oct-24
strategy                      : 14-Oct-24
biology                       : 20-Aug-24
philosophy                    : 16-Aug-24
maths                         : 07-Aug-24
genetics                      : 01-Aug-24
finance                       : 20-Jun-24
black-biography               : 12-Jan-24
espionage                     : 15-Dec-23
indian-fiction                : 20-Jul-23
economics                     : 15-Sep-22
games                         : 15-Sep-22
physics                       : 25-Dec-21
black-history                 : 26-Nov-21
eastern-biography             : 30-Sep-21
buddhism                      : 25-Aug-21
indian-society                : 12-Jan-21
science-fiction               : 05-Jan-21
african-fiction               : 11-Dec-20
scandinavian-thriller         : 25-Nov-20
black-fiction                 : 11-Oct-20
self-improvement              : 07-Aug-20
poetry                        : 23-Jun-20
eastern-fiction               : 07-Feb-20
sports                        : 02-Jan-20
product                       : 01-Dec-19
process                       : 06-Jul-19
indian-history                : 28-Aug-18
kids                          : 30-Nov-17
japanese-fiction              : 02-Jul-17
design                        : 05-May-15
marketing                     : 01-Jan-07
:end:


** Favorite authors

#+begin_src shell :results drawer :exports both
  ../item_recommender/recommend_book.py -a 30 books_list.csv
#+end_src

#+RESULTS:
:results:
List of best authors:

John Darwin
Anthony Marra
Patricia Highsmith
P. G. Wodehouse
Michael Korda
Jonathan Haidt
Mira Jacob
David Ignatius
Rohinton Mistry
Tania James
J.K. Rowling
Charles Cumming
Alexander Soderberg
John Sandford
David Downing
Jeffrey Archer
Amitav Ghosh
John Steinbeck
Jared Diamond
Russell Banks
Joseph Kanon
David McCullough
Richard Russo
Yaa Gyasi
Anthony Horowitz
Linwood Barclay
Tom DeMarco
Graham Greene
Steven E. Landsburg
Kiran Nagarkar
:end:


** Books to read by genre

#+begin_src shell :results drawer :exports both
  ../item_recommender/recommend_book.py -g brain -r 30 books_list.csv
#+end_src

#+RESULTS:
:results:
List of recommended books:

Models of the mind                                : Grace Lindsay        (4.4, brain,books-to-read-again)
How do we know ourselves?                         : David Myers          (4.0, brain)
Deep work                                         : Cal Newport          (4.0, brain)
Thinking, Fast and Slow                           : Daniel Kahneman      (4.1, brain,books-to-read-again)
The idea of the brain                             : Matthew Cobb         (4.0, brain)
Other minds: the octopus and the evolution of...  : Peter Godfrey-Smith  (4.0, biology,brain)
:end:


** Options

#+begin_src shell :results drawer :exports both
  ../item_recommender/recommend_book.py -h
#+end_src

#+RESULTS:
:results:
usage: recommend_book.py [-h] [-l] [-s NUM_READ_BOOKS]
                         [-r NUM_RECOMMEND_BOOKS] [-a NUM_AUTHORS] [-g GENRE]
                         [-ra AUTHOR]
                         books_file

Search for and recommend books using books_file. By default, show the 20 best
books to read next.

positional arguments:
  books_file

options:
  -h, --help            show this help message and exit
  -l, --list_genres
  -s, --list_read_books NUM_READ_BOOKS
  -r, --recommend_books NUM_RECOMMEND_BOOKS
  -a, --list_best_authors NUM_AUTHORS
  -g, --restrict_by_genre GENRE
  -ra, --restrict_by_author AUTHOR
:end:


* Sources for book recommendations

  - [[https://www.goodreads.com/list][Goodreads lists]]
  - [[https://en.wikipedia.org/wiki/List_of_winners_and_shortlisted_authors_of_the_Booker_Prize][Booker prize winners]]
  - [[https://en.wikipedia.org/wiki/Royal_Society_Prizes_for_Science_Books][Royal Society awards]] for science books
  - [[https://www.thehugoawards.org/hugo-history/][Hugo prize]] for science fiction
  - [[https://en.wikipedia.org/wiki/James_Tait_Black_Memorial_Prize#List_of_recipients][James Tait Black prize]] for biography
  - [[https://www.amazon.com/Oxford-Landmark-Science-19-book-series/dp/B08K79JYXS][Oxford Landmark Science]] series
  - [[https://en.wikipedia.org/wiki/DSC_Prize_for_South_Asian_Literature][DSC prize for South Asian literature]]
  - [[https://www.thejcbprize.org/#list][JCB prize for Indian fiction]]


* Tasks

** Archive                                                          :ARCHIVE:
*** DONE Look at JCB prize Indian books
:PROPERTIES:
:EFFORT:  00:15
:BENEFIT: 10
:RATIO: 0.40
:ARCHIVE_TIME: 2025-10-26 Sun 21:36
:END:
:LOGBOOK:
CLOCK: [2025-10-24 Fri 09:00]--[2025-10-24 Fri 09:28] =>  0:28
:END:
[2025-10-24 Fri]
