#+Title: List of books to read
#+FILETAGS: :Books:
#+STARTUP: content

* Books analysis


** Usual process to use this tool

   - Check the next 3 textbooks to read
   - Pick the next 3 non-textbooks to read from the list of 20 below
   - Have at least one textbook and one non-textbook to read at all times


** Next few books to read overall

#+begin_src shell :results drawer :exports both
../item_recommender/recommend_book.py -r 100 books_list.csv
#+end_src

#+RESULTS:
:results:
List of recommended books:

Storytelling with data                            : Cole Nussbaumer...   (4.3, design)
A different drummer                               : William Melvin...    (4.2, fiction)
Say Nothing                                       : Patrick Keefe        (4.4, western-history)
The Makioka Sisters                               : Junichiro Tanizaki   (4.0, japanese-fiction)
Anatomy of a Miracle: The End of Apartheid        : Patti Waldmeir       (4.1, eastern-history)
This Is Marketing: You Can't Be Seen Until You... : Seth Godin           (4.1, marketing,management)
Thus Bad Begins                                   : Javier Marias        (4.0, thriller)
A World Undone: A History of World War I          : G J Meyer            (4.2, western-history)
Tasting freedom: Octavius Catto                   : Daniel Biddle,...    (4.2, black-biography)
Ivan's War: Life and Death in the Red...          : Catherine Merridale  (4.0, eastern-history)
Conviction                                        : Denise Mina          (4.1, thriller)
Artificial intelligence: A modern approach        : Stuart Russell,...   (4.2, science,textbook)
Fatherland                                        : Robert Harris        (4.0, fiction)
The life you can save                             : Peter Singer         (4.5, philosophy,books-to-read-again)
Freshwater                                        : Akwaeke Emezi        (4.0, thriller)
Strategic Management                              : Charles Hill,...     (4.5, strategy,management,textbook,books-to-read-again)
The Balkans: Nationalism, War and the Great Powers: Misha Glenny         (4.1, eastern-history)
Quicksand: America's pursuit of power in the...   : Geoffrey Wawro       (4.1, western-history)
Bull Mountain                                     : Brian Panowich       (4.0, thriller)
The Sixth Conspirator                             : Max Byrd             (4.0, western-history)
Oryx and Crake                                    : Margaret Atwood      (4.0, science-fiction)
The overstory                                     : Richard Powers       (4.1, fiction)
The Pragmatic Programmer: From Journeyman to...   : Andy Hunt            (4.3, software,books-to-read-again)
Culture map                                       : Erin Meyer           (4.4, management,books-to-read-again)
What we owe the future                            : William MacAskill    (4.1, philosophy)
Over the edge of the world                        : Laurence Bergreen    (4.1, eastern-history)
Models of the mind                                : Grace Lindsay        (4.4, brain,books-to-read-again)
Working backwards                                 : Colin Bryar, Bill... (4.4, management,books-to-read-again)
Hell of a book                                    : Jason Mott           (4.1, fiction)
Statistics as principled argument                 : Robert Abelson       (4.1, maths)
Games of life                                     : Karl Sigmund         (4.0, maths)
Blueprint: How DNA makes us who we are            : Robert Plomin        (4.0, genetics,biology)
Moral tribes                                      : Joshua Greene        (4.0, philosophy)
Imperial twilight: the opium war                  : Stephen Platt        (4.3, eastern-history,books-to-read-again)
The Effective Executive: The Definitive Guide...  : Peter F. Drucker     (4.1, management,books-to-read-again)
Free to Choose: A Personal Statement              : Milton Friedman      (4.2, economics,books-to-read-again)
Build: An unorthodox guide to making things       : Tony Fadell          (4.0, management,product)
Ready for anything                                : David Allen          (3.9, self-improvement)
Clean hands                                       : Patrick Hoffman      (3.9, thriller)
The rise and reign of the mammals                 : Steve Brusatte       (4.0, biology,science)
The walking dead                                  : Gerald Seymour       (3.9, thriller)
Apocalypse Factory                                : Steve Olson          (4.0, western-history)
The Lion House                                    : Christopher de...    (4.0, eastern-history)
How do we know ourselves?                         : David Myers          (4.0, brain)
Before she knew him                               : Peter Swanson        (3.9, thriller)
Bangkok 8                                         : John Burdett         (4.0, eastern-fiction)
The garden of tales                               : Vijaydan Detha       (4.0, indian-fiction)
Forgotten armies: The fall of British Asia        : C. A. Bayly, Tim...  (3.9, eastern-history)
Sovereigns of the sea                             : Seema Alavi          (4.0, eastern-history)
The sense of style                                : Steven Pinker        (4.0, society)
Deep work                                         : Cal Newport          (4.0, brain)
Thinking,Fast and Slow                            : Daniel Kahneman      (4.1, brain,books-to-read-again)
Outlive                                           : Peter Attia          (4.0, science)
The War That Ended Peace: The Road to 1914        : Margaret MacMillan   (4.2, western-history,books-to-read-again)
Thinking in bets                                  : Annie Duke           (4.0, brain)
Algorithms to Live By: The Computer Science of... : Brian Christian      (4.2, maths,books-to-read-again)
Investment under uncertainty                      : Avinash Dixit,...    (4.0, maths)
A People's History of the United States           : Howard Zinn          (4.1, society,books-to-read-again)
The Moral Animal: Why We Are the Way We Are:...   : Robert Wright        (4.1, genetics,biology,books-to-read-again)
Northern Spy                                      : Flynn Berry          (4.0, thriller)
Crossing the Chasm: Marketing and Selling High-...: Geoffrey A. Moore    (4.0, marketing,books-to-read-again)
Self-help is like a vaccine                       : Bryan Caplan         (4.0, society)
A woman of no importance                          : Sonia Purnell        (4.0, western-biography,thriller)
The big picture                                   : Sean B. Carroll      (4.2, science,books-to-read-again)
Engines that move markets                         : Alasdair Nairn       (4.0, western-history,business)
The idea of the brain                             : Matthew Cobb         (4.0, brain)
Other minds: the octopus and the evolution of...  : Peter Godfrey-Smith  (4.0, biology,brain)
Automotive technology: a systems approach         : Jack Erjavec         (4.0, engineering,textbook)
Business model generation                         : Alex Osterwalder     (4.2, management,books-to-read-again)
Good Strategy Bad Strategy: The Difference and... : Richard P. Rumelt    (4.2, strategy,management,books-to-read-again)
Winter Tide                                       : Ruthanna Emrys       (3.8, science-fiction)
Building secure and reliable systems              : Heather Adkins       (4.0, engineering)
How to Measure Anything: Finding the Value of...  : Douglas W. Hubbard   (4.0, management,books-to-read-again)
Structures or why things don't fall down          : J. E. Gordon         (4.0, engineering)
Thinking Strategically: The Competitive Edge in...: Avinash K. Dixit     (4.0, strategy,management,books-to-read-again)
Superforecasting: The Art and Science of...       : Philip E. Tetlock    (4.1, science,books-to-read-again)
Practical Ethics                                  : Peter Singer         (4.1, philosophy,books-to-read-again)
The Happiness Hypothesis                          : Jonathan Haidt       (4.1, philosophy,books-to-read-again)
Knowledge,reality and value                       : Michael Huemer       (4.1, philosophy,textbook,books-to-read-again)
Capitalism and Freedom                            : Milton Friedman      (3.9, economics,books-to-read-again)
The Myth of the Rational Voter: Why Democracies...: Bryan Caplan         (3.9, society,books-to-read-again)
The Halo Effect: ... and the Eight Other...       : Philip M. Rosenzweig (3.9, management,books-to-read-again)
Your inner fish                                   : Neil Shubin          (4.0, biology,books-to-read-again)
Game theory: an introduction                      : Steve Tadelis        (4.0, maths,textbook,books-to-read-again)
The God Delusion                                  : Richard Dawkins      (3.9, science,books-to-read-again)
Crucial Conversations                             : Kerry Patterson      (4.0, management,books-to-read-again)
King                                              : Jonathan Eig         (4.0, black-biography,books-to-read-again)
Bubble or revolution?                             : Neel Mehta           (4.0, finance,maths,books-to-read-again)
How big things get done                           : Bent Flyvbjerg       (4.0, management,books-to-read-again)
The missing billionaires                          : Victor Haghani       (4.0, maths,finance,textbook,books-to-read-again)
The Grid                                          : Philip Schewe        (4.0, engineering,books-to-read-again)
An introduction to decision theory                : Martin Peterson      (3.8, maths,textbook,books-to-read-again)
CMMI for Development: Guidelines for Process...   : Mary Beth Chrissis   (3.5, process,books-to-read-again)
:end:


** Next textbook to read

#+begin_src shell :results drawer :exports both
../item_recommender/recommend_book.py -r 20 -g textbook books_list.csv
#+end_src

#+RESULTS:
:results:
List of recommended books:

Fundamentals of software architecture             : Mark Richards,...    (4.3, software,engineering,textbook)
Bayesian data analysis                            : Andrew Gelman        (4.2, maths,textbook)
Artificial intelligence: A modern approach        : Stuart Russell,...   (4.2, science,textbook)
Strategic Management                              : Charles Hill,...     (4.5, strategy,management,textbook,books-to-read-again)
Automotive technology: a systems approach         : Jack Erjavec         (4.0, engineering,textbook)
Knowledge,reality and value                       : Michael Huemer       (4.1, philosophy,textbook,books-to-read-again)
Game theory: an introduction                      : Steve Tadelis        (4.0, maths,textbook,books-to-read-again)
An introduction to decision theory                : Martin Peterson      (3.8, maths,textbook,books-to-read-again)
:end:


** Books that I have read before but should read again

#+begin_src shell :results drawer :exports both
../item_recommender/recommend_book.py -r 10 -g books-to-read-again books_list.csv
#+end_src

#+RESULTS:
:results:
List of recommended books:

The life you can save                             : Peter Singer         (4.5, philosophy,books-to-read-again)
Strategic Management                              : Charles Hill,...     (4.5, strategy,management,textbook,books-to-read-again)
The Pragmatic Programmer: From Journeyman to...   : Andy Hunt            (4.3, software,books-to-read-again)
Culture map                                       : Erin Meyer           (4.4, management,books-to-read-again)
Models of the mind                                : Grace Lindsay        (4.4, brain,books-to-read-again)
Working backwards                                 : Colin Bryar, Bill... (4.4, management,books-to-read-again)
Imperial twilight: the opium war                  : Stephen Platt        (4.3, eastern-history,books-to-read-again)
The Effective Executive: The Definitive Guide...  : Peter F. Drucker     (4.1, management,books-to-read-again)
Free to Choose: A Personal Statement              : Milton Friedman      (4.2, economics,books-to-read-again)
Thinking,Fast and Slow                            : Daniel Kahneman      (4.1, brain,books-to-read-again)
:end:


** Recently read

#+begin_src shell :results drawer :exports both
../item_recommender/recommend_book.py -s 50 books_list.csv
#+end_src

#+RESULTS:
:results:
List of read books:

Henry Ford                                        : Vincent Curcio       (21-Jun-25, 5.0)
Stone mattress                                    : Margaret Atwood      (10-Jun-25, 5.0)
Sloan rules                                       : Henry Farber         (20-May-25, 5.0)
The sleep prescription                            : Arik Prather         (13-Apr-25, 5.0)
The gatekeepers                                   : Chris Whipple        (13-Apr-25, 5.0)
King Richard                                      : Michael Dobbs        (13-Apr-25, 5.0)
Secure software systems                           : Erik Fretheim        (05-Jan-25, 2.0)
Amos Walker: The Complete Story Collection        : Loren D. Estleman    (04-Jan-25, 1.0)
Talking to the enemy: faith, brotherhood,and...   : Scott Atran          (14-Dec-24, 1.0)
A cartoon history of the universe                 : Larry Gonick         (14-Dec-24, 2.0)
Crossing Point                                    : James Glickman       (01-Dec-24, 4.0)
Magdalena: River of dreams                        : Wade Davis           (26-Oct-24, 2.0)
Only the paranoid survive                         : Andrew Grove         (26-Oct-24, 2.0)
Becoming Trader Joe                               : Joe Coulombe         (14-Oct-24, 5.0)
The law of innocence                              : Michael Connelly     (25-Aug-24, 5.0)
The shadow district                               : Arnaldur Indridasson (20-Aug-24, 4.0)
Life on a young planet: the first 3 billion years : Andrew Knoll         (20-Aug-24, 1.0)
Life 3.0: Being Human in the Age of Artificial... : Max Tegmark          (02-Aug-24, 1.0)
The Florentines                                   : Paul Strathern       (02-Aug-24, 5.0)
The vital question: Energy, evolution and the...  : Nick Lane            (01-Aug-24, 1.0)
Shape                                             : Jordan Ellenberg     (20-Jul-24, 5.0)
Scaling people                                    : Claire Hughes...     (05-Jul-24, 3.0)
The missing billionaires                          : Victor Haghani       (20-Jun-24, 4.0)
The silk roads                                    : Peter Frankopan      (12-Jun-24, 2.0)
Trillion dollar coach                             : Eric Schmidt,...     (05-Jun-24, 4.0)
High output management                            : Andrew Grove         (30-May-24, 5.0)
Measure what matters                              : John Doerr           (10-Apr-24, 4.0)
The rebellious life of Mrs. Rosa Parks            : Jeanne Theoharis     (10-Jan-24, 5.0)
How the world really works                        : Vaclav Smil          (01-Jan-24, 5.0)
An honorable man                                  : Paul Vidich          (15-Dec-23, 4.0)
The Art of Action                                 : Stephen Bungay       (01-Dec-23, 2.0)
Ponniyil Selvan - book 1                          : Kalki                (20-Jul-23, 5.0)
The diamond eye                                   : Kate Quinn           (05-Jul-23, 3.0)
A failed empire                                   : Vladislav Zubok      (15-Feb-23, 3.0)
Lenin the dictator                                : Victor Sebestyen     (25-Nov-22, 5.0)
Nuclear Folly                                     : Serhii Plokhy        (04-Oct-22, 5.0)
Who gets what and why                             : Alvin Roth           (15-Sep-22, 3.0)
These women                                       : Ivy Pochoda          (25-Jul-22, 5.0)
The Elephant in the Brain                         : Kevin Simler         (18-Jul-22, 5.0)
The Best Place to Work: The Art and Science of... : Ron Friedman         (07-Jul-22, 5.0)
Tumbling                                          : Diane McKinney-...   (15-Apr-22, 4.0)
Infectious: Pathogens and how we fight them       : John Tregoning       (10-Apr-22, 1.0)
Confessions                                       : Kanae Minato         (21-Feb-22, 4.0)
Sync: the emerging science of social order        : Steven Strogatz      (27-Jan-22, 2.0)
The dead are arising: The life of Malcolm X       : Les Payne            (24-Jan-22, 4.0)
Designing data-intensive applications             : Martin Kleppmann     (15-Jan-22, 5.0)
Alan Turing: The Enigma                           : Andrew Hodges        (12-Jan-22, 4.0)
Fundamentals                                      : Frank Wilczek        (25-Dec-21, 1.0)
Leaving Berlin                                    : Joseph Kanon         (18-Dec-21, 4.0)
The Transformation of the World: A Global...      : Jurgen Osterhammel   (18-Dec-21, 2.0)
:end:



** List of genres

#+begin_src shell :results drawer :exports both
  ../item_recommender/recommend_book.py -l books_list.csv
#+end_src

#+RESULTS:
:results:
List of categories and read-dates:
western-biography             : 21-Jun-25
brain                         : 21-Jun-25
japanese-fiction              : 21-Jun-25
western-fiction               : 10-Jun-25
western-history               : 13-Apr-25
science                       : 13-Apr-25
engineering                   : 05-Jan-25
software                      : 05-Jan-25
thriller                      : 04-Jan-25
society                       : 14-Dec-24
eastern-history               : 14-Dec-24
fiction                       : 01-Dec-24
management                    : 26-Oct-24
books-to-read-again           : 14-Oct-24
strategy                      : 14-Oct-24
biology                       : 20-Aug-24
textbook                      : 16-Aug-24
philosophy                    : 16-Aug-24
maths                         : 07-Aug-24
genetics                      : 01-Aug-24
finance                       : 20-Jun-24
black-biography               : 12-Jan-24
espionage                     : 15-Dec-23
indian-fiction                : 20-Jul-23
economics                     : 15-Sep-22
games                         : 15-Sep-22
physics                       : 25-Dec-21
black-history                 : 26-Nov-21
eastern-biography             : 30-Sep-21
buddhism                      : 25-Aug-21
indian-society                : 12-Jan-21
science-fiction               : 05-Jan-21
african-fiction               : 11-Dec-20
scandinavian-thriller         : 25-Nov-20
black-fiction                 : 11-Oct-20
self-improvement              : 07-Aug-20
poetry                        : 23-Jun-20
eastern-fiction               : 07-Feb-20
sports                        : 02-Jan-20
product                       : 01-Dec-19
process                       : 06-Jul-19
indian-history                : 28-Aug-18
kids                          : 30-Nov-17
design                        : 05-May-15
marketing                     : 01-Jan-07
business                      : 01-Jan-00
:end:


** Favorite authors

#+begin_src shell :results drawer :exports both
  ../item_recommender/recommend_book.py -a 30 books_list.csv
#+end_src

#+RESULTS:
:results:
List of best authors:

John Darwin
Anthony Marra
Patricia Highsmith
P. G. Wodehouse
Michael Korda
Jonathan Haidt
Mira Jacob
David Ignatius
Rohinton Mistry
Tania James
J.K. Rowling
Charles Cumming
Alexander Soderberg
John Sandford
David Downing
Jeffrey Archer
Amitav Ghosh
John Steinbeck
Jared Diamond
Russell Banks
Joseph Kanon
David McCullough
Richard Russo
Yaa Gyasi
Anthony Horowitz
Linwood Barclay
Tom DeMarco
Graham Greene
Steven E. Landsburg
Kiran Nagarkar
:end:


** Books to read by genre

#+begin_src shell :results drawer :exports both
  ../item_recommender/recommend_book.py -g brain -r 30 books_list.csv
#+end_src

#+RESULTS:
:results:
List of recommended books:

Models of the mind                                : Grace Lindsay        (4.4, brain,books-to-read-again)
How do we know ourselves?                         : David Myers          (4.0, brain)
Deep work                                         : Cal Newport          (4.0, brain)
Thinking,Fast and Slow                            : Daniel Kahneman      (4.1, brain,books-to-read-again)
Thinking in bets                                  : Annie Duke           (4.0, brain)
The idea of the brain                             : Matthew Cobb         (4.0, brain)
Other minds: the octopus and the evolution of...  : Peter Godfrey-Smith  (4.0, biology,brain)
:end:


** Options

#+begin_src shell :results drawer :exports both
  ../item_recommender/recommend_book.py -h
#+end_src

#+RESULTS:
:results:
usage: recommend_book.py [-h] [-l] [-s NUM_READ_BOOKS]
                         [-r NUM_RECOMMEND_BOOKS] [-a NUM_AUTHORS] [-g GENRE]
                         [-ra AUTHOR]
                         books_file

Search for and recommend books using books_file. By default, show the 20 best
books to read next.

positional arguments:
  books_file

options:
  -h, --help            show this help message and exit
  -l, --list_genres
  -s, --list_read_books NUM_READ_BOOKS
  -r, --recommend_books NUM_RECOMMEND_BOOKS
  -a, --list_best_authors NUM_AUTHORS
  -g, --restrict_by_genre GENRE
  -ra, --restrict_by_author AUTHOR
:end:


* Sources for book recommendations

  - [[https://www.goodreads.com/list][Goodreads lists]]
  - [[https://en.wikipedia.org/wiki/List_of_winners_and_shortlisted_authors_of_the_Booker_Prize][Booker prize winners]]
  - [[https://en.wikipedia.org/wiki/Royal_Society_Prizes_for_Science_Books][Royal Society awards]] for science books
  - [[https://www.thehugoawards.org/hugo-history/][Hugo prize]] for science fiction
  - [[https://en.wikipedia.org/wiki/James_Tait_Black_Memorial_Prize#List_of_recipients][James Tait Black prize]] for biography

  - [[https://en.wikipedia.org/wiki/DSC_Prize_for_South_Asian_Literature][DSC prize for South Asian literature]]
  - [[https://www.thejcbprize.org/#list][JCB prize for Indian fiction]]
  - [[https://en.wikipedia.org/wiki/Crossword_Book_Award][Crossword award for Indian literature]]
