#+TITLE: Books and research on the brain
#+FILETAGS: :Brain:Science:
#+STARTUP: overview, hideallblocks

* The Dreyfus model of skill acquisition                             :Review:
:PROPERTIES:
:ID:       1b62c6dd-c98f-45c4-b85d-d4162a880e2b
:END:

We must adopt the systems thinking mindset that everything is
interconnected and, hence, everything must be considered in its
context. The journey towards this underlying mindset is fundamental to
skill acquisition.

The Dreyfus model of skill acquisition can be applied to the learning
process for any skill. The model describes continuous growth through
the phases of Novice, Competent, Proficient, and Expert.

Most people do not achieve the Expert phase in a skill although they
may think they have achieved it.

To advance through the phases of skill acquisition, a person must
spend time doing the underlying activity. About 10,000 hours is a good
metric for the amount of effort required to get from Novice to
Expert.

However, just spending time in a phase doing the same activities over
and over is not enough to advance to the next phase. The person must
reflect upon the progress and adjust their approach. This provides a
feedback loop that is critical to success. A good example is doing
your tax returns. Each year, you follow a fixed process to do your
taxes. However, most people stay at the Novice phase in tax return
filing.

In the Novice phase, you need context-free recipes and rules to do the
work. Unfortunately, such context-free rules are tedious to
document. Also, adhering strictly to context-free rules can result in
inefficiency and lack of adaptability.

In the Competent phase, you start to break away from such
context-free rules. You are able to skim the rules to learn and can
rely upon your intuition. This intuition has been built up by practice
in the Novice phase. The process of skimming the rules builds up the
relevant focus on the context i.e. you start to pick out the items
from the context that matter most to the work at hand.

From the Proficient phase, you start to use reflection and
self-adjustment based on your intuition and understanding of the
overall process. This can be thought of as a feedback mechanism. In
the Agile mindset, this can be the retrospective and the improvements
from the retrospective.

From the Proficient through the Expert phases, there is a phase
transition in efficiency and intuition. The practitioner realizes that
they are part of a system and yet they are not bogged down by the
complexity of the overall system. They are able to identify the key
elements of the system that provide leverage for the activity at hand.

An expert need not be a good teacher. Often, an expert does not have
the patience to explain why they understand something
intuitively. However, what they do appears effortless to the
Beginner. Further, they are able to adapt their processes in the
context of the larger system.

In order to improve the level of proficiency, the nursing industry
went through significant changes. Their lessons can be summarized as
follows.
- Individuals must accept the responsibility for continuous improvement.
- Individuals must be able to practise as an individual contributor
  throughout their career.
- Management must set up compensation and recognition such that
  individuals can keep practising their expertise rather than turning
  into managers.
- All must beware of the tools trap i.e. assuming that tools alone can
  bring about process excellence.


** Andy Hunt: Software isn't designed in a tool, it is created in our heads. :quotes:


** References

- Andy Hunt, Pragmatic Thinking and Learning
- Dreyfus brothers, [[https://drive.google.com/file/d/0B5vaNNyT6fShdHVDM2I1cDhmSHc/view?usp=drive_link&resourcekey=0-4LNorgv2lUJo_5BfAC5YBg][Acquiring New Skills]]


* Principles of effective teaching                                   :Review:

1. Take the difficulty level you naturally want to use.  Now divide it
   by 10.  Remember: The material is only obvious to you because you
   are the teacher.  It is non-obvious to your students because they
   are the students.

2. If you're teaching at MIT or Caltech, you are now at the right
   difficulty level.  If you're anywhere else, divide by 10 again.
   Remember: Even smart people are, at first, terrible at almost
   everything.

3. Don't expects students to "figure things out for themselves."
   Start with model problems, then work through them at a snail's
   pace.

4. Once you have shown students clear model problems, assign a bunch
   of slightly different problems.  Tell them to get to work.

5. If your students do less than 75% of their problems correctly, your
   problems are still too hard.  Walk them through problems so easy
   you can't even imagine their inability to do them.  This will
   improve their knowledge and your imagination.

6. If your students do 75-94% of their problems correctly, give them
   more practice.  Drill, drill, drill.

7. If your students do 95%+ of their problems correctly, they are
   ready to advance.  Even then, remember that they are likely to
   forget unless you periodically give them refresher work (except for
   highly sequential subjects).

8. Never confuse logic with psycho-logic – and remember that
   psycho-logic is much more important for pedagogy.  What does that
   mean?  Don’t expect students to grasp that A–>B simply because
   A–>B.  Your job is to make truisms seem obvious to ignorant minds.
   Vary your examples.  Mix it up.  Switch around.  Use repetition.
   Use repetition.  Use repetition.

9. Look at your students' faces.  If they are bored, be more fun.
   Tell jokes.  Mock yourself.  Clown around.  Playfully exaggerate
   all emotions.  Throw your pride aside; a teacher is an entertainer
   or he is a failure.

10. Look at your students' faces.  If they are frustrated, be more
    patient.  Never add negative emotion on top of negative emotion.
    If a student is upset, be a model of mild-mannered stoicism.
    Without fail.  Without fail.  Without fail.

11. Look at your students' faces.  If they feel like their efforts are
    pointless, sell them your subject.  Tell them what learning your
    subject will do for them, even if the only honest answer is, "You
    need this for graduation."

12. Look at your students’ faces.  If they don’t trust you, earn their
    trust.  Don’t merely avoid deception; be frank.  Don’t sugarcoat
    the world, even for little kids.  Unless the ugly truth will give
    them nightmares or get you fired, share it with equanimity.

13. Look at your students’ faces.  If you can’t read their emotions,
    ask them questions.  Press them.  Find out what they already know.
    Find out what confuses them.  Find out whether they are happy or
    sad or think you’re crazy.  Accept their answers beatifically and
    adjust your pedagogy to fit the students you actually have.

14. Maintain discipline.  If you have a schedule, stick to it.  If you
    announce a punishment, stick to it.  If you promise a break, stick
    to it.  Education is for the students, but it is not a democracy.
    Listen carefully to what your students say, but only reform from a
    position of strength.  Don’t be generous; be magnanimous!  If you
    think this contradicts Principle #9, know that you are wrong.  Act
    like a jester – but rule like a king.

15. All of these principles are optimized for one-on-one teaching.  If
    you’re teaching more students, you have to strike a balance.  You
    will always shortchange someone.  Sorry, that’s a classroom –
    another point in favor of homeschooling.

** Morpheus: Neo, there’s a difference between knowing the path and walking the path. :quotes:

** References

- Bryan Caplan, [[https://www.econlib.org/teaching-teaching/][Teaching teaching]]

* Creativity and learning                                            :Review:
:PROPERTIES:
:ID:       8b5f3072-ad2e-4005-9934-cd3ae189e99f
:END:

The brain can typically work in a Focused mode or a Diffuse mode.

The Focused mode, or L-mode, is most useful when you are executing on
a task. The Diffuse mode is when the mind is free and wanders. Western
cultures especially emphasize spending time in Focused mode. However,
to get creative ideas, you need to spend time in Diffuse mode. These
modes are often called the L-mode (L for linear) and R-mode
respectively.

The Diffuse mode, or R-mode, allows the brain to work on the tough
problems and discover connections that you cannot find in Focused
mode. The brain does Diffuse mode thinking when you go on a run or a walk
without any other stimuli.

When you have ideas, you must note them down. Have a method handy to
note down ideas as soon as they come to you. You'll notice that, the
more you start to write down and work on your ideas, the more ideas
you start having. Harness and clean up those ideas frequently and keep
building upon them. Finally, have a plan to act upon ideas.

There are many ways to help the R-mode in its work: doodling, drawing
mind maps that enhance non-linear relationships, just walking or doing
other mundane tasks, thinking in metaphors, writing down what you are
thinking, etc.

** References

- "Pragmatic Thinking and Learning" by Andy Hunt
- [[https://www.coursera.org/learn/learning-how-to-learn/][Learning to learn]] Coursera course


* Models of the brain                                                :Review:


** Making and maintaining memories

   A neural network can be configured such that it has certain
   low-energy states that act as attractors. Such neural networks are
   known as Hopfield networks. When an arbitrary input
   is provided to the neural network, the neural network converges to
   one of these attractors. This can be used to simulate the behavior
   of the brain where certain stimuli can cause the brain to remember
   old events or patterns.

   However, Hopfield networks have discrete attractors and do not
   match well the real-life behavior of attractors that are close to
   each other. For instance, you may remember something to be a shade
   of blue that is close to another shade. To simulate such behavior,
   a ring structure where similar memories are close to each other
   works better.

   In either case, these networks are only crude approximations of
   what really happens in the brains. The actual neural networks
   behave in a very complicated and messy fashion that can not be
   cleanly described through such models.


** References

- Models of the mind, Grace Lindsay


** Bertrand Russell: The trouble with the world is that the stupid are cocksure and the intelligent full of doubt. :quotes:


* Moral reasoning                                                    :Review:

The principles of moral psychology are:
1. Intuitions come first, strategic reasoning second.
2. There's more to morality than harm and fairness (WEIRD morality).
3. Morality binds and blinds.

Reasoning functions like a press secretary who automatically justifies
any position taken by the president.

When we have to answer a hard question, we generally use the strategy
of looking for a simple case that we know about that provides one
answer to the question, then we test if the answer makes sense and
then we stop. For instance, if we're asked if minimum wages are a good
idea, we think of an aunt who would benefit from having a minimum
wage. Since it makes sense that her situation would be better with a
minimum wage, we then conclude that minimum wages is a great
idea. We do not take the time to consider any evidence against minimum
wage.

There are studies that show that, even when we are informed that all
human beings have biases, we use that information to adjust our view
of others but not of ourselves.

Reasoning has evolved not to help us find truth but to help us engage
in arguments, persuasion, and manipulation in the context of
discussions with other people.

Understanding the argument from the other side is hard because our
confirmation bias is a built-in feature (of an argumentative mind),
and not a bug that can be removed (from a platonic mind).

Reasoning can take us to almost any conclusion we want to reach,
because we ask “Can I believe it?” when we want to believe something,
but “Must I believe it?” when we don’t want to believe. The answer is
almost always yes to the first question and no to the second.

The moral domain is unusually narrow in WEIRD (Western, educated,
industrialized, rich, democratic) cultures, where it is largely
limited to the ethic of autonomy (i.e., moral concerns about
individuals harming, oppressing, or cheating other individuals). It is
broader—including the ethics of community and divinity—in most other
societies, and within religious and conservative moralities.

Ethics of community: It would be nice if human beings could love all
people or forms of life. However, that's not what evolution has
programmed us to do. Instead, we are programmed to be able to live and
be loyal to a group with shared characteristics and common goals where
free ridership is suppressed. Being part of such a group gives us a
higher purpose.

Homecoming football games can be understood as opportunities for
people to become part of one large group with a common purpose. If you
look only at the cost (injury to players, alcoholism etc), you're
missing the full picture.

People have hypersensitive agency detectors: they see an agent behind
an action even when there isn't one. Evolution programmed us to have a
high number of false positives in this aspect. This was the first step
in developing religion. The second step was probably the cultural
development of religious tribes through group selection. Groups that
had religious beliefs may have been more cohesive and lasted longer
than groups that did not.

Research shows that religious communes that require significant
sacrifices from its members survive longer than secular communes, even
if the secular ones demanded sacrifices. Investing the needs of
sacrifice in a higher being may make them more likely to be
followed and may contribute to the integrity of the organization.

** References

- The righteous mind, Jonathan Haidt

* The architecture of knowledge                                      :Review:

Think of all knowlege as a pyramid. At the top of the pyramid is the
small set of things you know.

Below that is a broader section of the
things you know you don't know. You are aware that these things exist
but you haven't delved into them in detail. Perhaps you have a Novice
level knowledge of them or you just have awareness that they exist.

Finally, at the base of the pyramid are the much larger set of things
that you don't know you don't know. They exist out there but you are
not even aware that they exist. Further, that base is growing faster
in time than either of the two sections above because the two sections
above only grow at the rate that you can learn.

* Poetic naturalism                                                  :Review:

Poetic naturalism - Naturalism is the belief that the world revealed
through scientific inquiry is the only true world.

Poetic implies that there are many ways of describing this natural
world. All the good ways of talking about the world must be consistent
with each other and with the observed reality of the world. The best
way of describing the world depends upon what you want to achieve.

One way might be derived from another. For instance, fluid dynamics
can be a macro-level view of a fluid derived from the quantum-level
understanding of it. In this case, the quantum level view is called
fundamental, and the fluid dynamic view is called emergent. Each model
is autonomous and doesn't rely upon the other. Each model has its
own domain of applicability.

Phase transitions happen when the underlying system moves from one
domain of applicability to another. For instance, the big bang, then
atoms, then life, then multi-cellular organisms, etc.

Sometimes, these models can be hierarchical, starting from a
fundamental model and becoming more coarse-grained. More
coarse-grained models allow for easier computation and cognition to
get insights. However, they may have a limited domain of
applicability.

You can think of probability in two ways. One way is that, if you
simulate an event infinite times, the probability of the event tells
you how often that event will happen. However, Bayesians think of the
probability of an event as the credence that you give it in the
presence of uncertainty. With this method, you never give certainty to
any belief because there is always a chance that you will be proven
wrong by later events. As events unfold, you update the credence you
give to the event by using the Bayesian formula.

There are three features that characteristize life as we know
it. They are compartmentalization, metabolism, and replication with
variation.

Compartmentalization means that a living form typically has a membrane
that separates it from the inside. This is relatively easy to
achieve. For example, Thomas Schelling showed that, if the following properties
hold:
1. A community is represented by Xs and Os,
2. Each of them is unhappy if they are surrounded by 70% or more of
   the other, and
3. When they are unhappy, they're able to move to a random open slot
then you reach an equilibrium where the Xs and Os are largely
segregated.

This could be interpreted as membranes around the Xs and Os.

In biology, lipids are commonly used for membranes. They have
hydrophilic heads and hydrophobic tails which have the capacity to be
"happy".

Most scientists believe that replication happened first before
metabolism. Our cells are constructed so that information is stored in
the DNA while the actual work is done through proteins. The
translation from the blueprint to work is done by an intermediate
layer called mRNA in the ribosomes.

** References

- Sean Carroll, "The big picture"

* Types of bias                                                      :Review:

  This note lists some key biases that affect our thinking. Methods to
  overcome bias are noted here.

  The acronym to remember is FFRACASS.


** Focusing bias

   Nothing In life is as important or as useful as you think it is.

   For instance, there is not a lot of correlation between wealth and
   happiness. Paraplegics are not as unhappy as non-paraplegics think
   they are. Living in California won't make you as happy as you think
   it will.

   Similarly, people tend to look at new initiatives or new processes
   as cure-alls. They are usually not.


** First conclusion bias

   When we see a first conclusion that matches our inherent biases,
   our mind shuts down to other possible explanations.  As Charlie
   Munger famously pointed out, the mind works a bit like a sperm and
   egg: the first idea gets in and then the mind shuts.


** Representativeness bias

   We tend to not use base rates in our forecasting.

   For example, when determining the success of a new project, we
   discount the failure rate of previous similar projects.

   Another example: when asked "Donald Jones is of a retiring
   nature. Is it more likely that he is a salesman or a
   librarian?", most people guess that he is a
   librarian. However, by Bayes' theorem:

   P[librarian/retiring] > P[salesman/retiring] <=>
   P[retiring/librarian] / P[retiring/salesman] > P[salesman] /
   P[librarian]

   In the base population of all men, salesmen are much more
   likely than librarians. The probability of a male librarian
   being retiring would have to be significantly higher than that
   of a male salesman being retiring to overcome that.


** Availability bias

   We tend to more easily recall what is more vivid and more recent.
   For instance, people tend to overestimate the danger of an air
   crash or a terror attack.


** Confirmation bias

   We tend to look for confirmations of long-held wisdom rather than
   violations. Jonathan Haidt makes this point in the context of
   morality.


** Attribution bias

   We tend to believe that what people do reflects who they are. As a
   consequence, we overestimate how consistent others' behavior will
   be.

   This is also called Fundamental Attribution Error.


** Social desirability bias

   We tend to seek safety in numbers and will look for social guidance
   of our behavior.

   This instinct creates a cohesive sense of cooperation and culture
   which would not otherwise be possible but also leads us to do
   foolish things if our group is doing them as well.


** Survivorship bias

   We over-attribute success to things done by a successful agent
   rather than to randomness or luck. Also, we often learn false
   lessons by exclusively studying victors without seeing all the
   accompanying losers who acted in the same way but did not
   succeed. This has been highlighted in the business world by Phil
   Rosenzweig.
