#+Title: Chip industry
#+FILETAGS: :Technology:Semiconductors:Chips:

* PC chip industry

  As of early 2022, the PC chip industry has seen significant growth
  in the first two years of the COVID pandemic (2020-22).  AMD has
  ~20% share in the industry and has gained a large market share from
  Intel.

  PC shipments increased to about 340M units in CY21, compared
  to an average of 265M units in the five years comprising CY15
  through CY19. Forecasts are that this higher level will stay steady
  but will not increase significantly. Intel is depending upon the
  revenue from the PC market to fund an expensive effort to build up
  manufacturing to compete with TSMC.

  Other competitors are ARM (Apple used ARM technology for its
  in-house chips) and Qualcomm which is making in-roads into the
  market with Snapdragon.


* Relative sizes of market

  In 2022, the units sold ever year are as follows.
     - 1.5B smart phones (~150M smart-phones/OEM)
     - 340M PCs/laptops
     - 80M cars


* TSMC

  Every car has about 20 MCUs on average.
  About 70% of all MCUs are manufactured by TSMC.
  Yet, automotive chips are only 3% of TSMC revenue.
