#+TITLE: The culture map by Erin Meyer
#+FILETAGS: :BookNotes:

Different cultures fall in different places on the scales of various
activities. We can divide them into a few specific activities. Note
that a culture or country's position on one activity may not correlate
with the expected position on another activity. Hence, each activity
must be considered separately.

* Communication (low-context vs high-context)

  In low-context cultures, good communication is precise, simple and
  clear. Messages are given and understood at face value. Repetition
  is appreciated if it helps clarify.

  The US, Netherlands, Canada fall on this end of the spectrum.

  In high-context cultures, good communication is nuanced and
  layered. Messages are both spoken and read between the
  lines. Messages are often implied but not plainly expressed.

  Many of the Asian countries, Russia, France fall on this end of the
  spectrum. These tend to be countries with a long shared history with
  an orientation towards relationships.

  Note that when two cultures meet, what matters is the relative
  position of the cultures wrt each other and not the absolute
  positions.


* Evaluation (direct vs indirect feedback)

  Direct negative feedback is when negative feedback is provided bluntly
  and those messages stand alone without being softened by positive
  ones. Criticism can often be done in public.

  Indirect is the opposite.

  Although Western countries like the US, UK and Canada use
  low-context communication, they also do not give direct negative
  feedback. On the other hand, in the Netherlands, Germany and Russia,
  direct negative feedback is often practised. The Asian countries
  typically practise indirect negative feedback also.


* Persuasion (principles-first vs applications-first)

  Certain cultures like the US use applications-first or inductive
  reasoning. For instance, in the US, in math class, you learn a
  formula first and apply it many times before you understand the
  concept behind it.

  In contrast, in a French math class, you do not apply a formula
  until you've understood the fundamental concept. This is called
  principles-first or deductive reasoning.

  As a result, in the US or in the UK, you are expected to get to a
  conclusion quickly while, in the rest of Europe, you may be expect
  to lay out a foundation before presenting your conclusion.

  Asian cultures use a different approach altogether, one based on
  a holistic context. In a study comparing photos of people taken by
  Americans and Japanese, the Americans took close-up pictures showing
  all the features of the subject's face while the Japanese showed the
  person in his or her environment. Thus, Asian cultures typically
  look at a person holistically, in the context of his or her
  environment. So, for example, you may not be effective if you set
  individual direct reports' goals in isolation. It may be better to
  spend a lot of time describing the big picture and how everyone's
  work fits into it. Japanese companies often use a system where an
  initial draft of a proposal is circulated at one level of management
  and everyone gets to provide feedback. Once there is agreement
  within that level, the document moves up to the next level and so
  on. While this process can be slow, it also gives everybody a chance
  to provide input.


* Leadership (egalitarian vs hierarchical)

  Many Scandinavian cultures stress flat hierarchies where the boss is
  just "one of us". Communications can often skip leadership levels in
  such cultures. In such egalitarian cultures, it's OK to disagree
  with the boss openly.

  In contrast, many Asian cultures stress strict hierarchies. For
  example, it may be OK for the boss to drive a bicycle in Sweden but
  not in China. In such cultures, the best boss is a strong director
  who leads from the front. Communications follow set hierarchical
  lines both internally within the company and externally with
  customers and suppliers. Usually, an effort is made to defer to the
  boss's opinion in public.


* Decision making (top-down vs consensus)

  Usually, egalitarian cultures also have decision making by
  consensus. The Americans are the only exception here. In the US, the
  leadership culture is generally egalitarian but Americans also
  believe in decisions being made quickly and at the top.

  Usually, hierarchical cultures have top-down decision
  making. Germany is the exception here that combines hierarchical
  culture with consensus building.

  For Americans, decisions are only a snapshot. Over time, the
  decision can be changed based on new available information. Hence,
  it's more like a decision with a small "d". For
  Germans, on the other hand, after a long period of internal
  consensus-building, a decision is usually more stable and not easily
  changed. That's more like a decision with a big "D".


* Building trust (affective vs cognitive)

  The Chinese have a term called guanxi which implies the time, energy
  and effort to build a personal connection. This means that you have
  to forget the deal for a while, go out, share drinks and build an
  emotional connection. Many Japanese use drinking parties to forge
  connections. This is often termed "nomunication" from the Japanese
  term "nomu" meaning "to drink". While this seems wasteful to Western cultures,
  it is essential to do business in China and other Asian cultures.

  Affective trust arises from feelings of emotional closeness, empathy
  or friendship while cognitive trust arises from confidence in skills
  and accomplishments. American culture requires a separation of
  emotions from business and trust in business is usually built from
  cognitive trust. In American business culture, it is generally not
  encouraged to share personal problems with business
  connections. Even if you have ice-breaker activiies, teh
  participants get back to a business relationship afterwards.  In
  China or Brazil, on the other hand, "business is personal". As
  businesses become more global, there has been a shift in mindset
  from cognitive to more affective trust.

  The levels of interaction at each level of relationship varies
  across cultures. The peach vs coconut model is often used to
  describe this. In peach cultures like the US or Brazil, people tend
  to be friendly with others they have just met; smiling frequently at
  strangers, moving to first-name usage and sharing information abut
  themselves. However, after some friendly interaction, you get to the
  hard shell of the peach pit where the peach protects its real
  self. On the other hand, Polish, French or German cultures can seem
  like coconut cultures. In these, people are generally more closed
  like the shell of a coconut. They rarely smile at
  strangers. Gradually, they become warmer and friendlier.


* Disagreeing (confrontational vs harmonizing)

  Confucius talks about the five types of relations that must be
  maintained in constant harmony. Japanese culture highly values
  harmony over quarreling. In Asian societies, disagreements have to
  be expressed while maintaining harmony and saving face for the
  individuals. On the other hand, in French culture, for example,
  people are encouraged from an early age to disagree publicly. They
  see open debate as the way to get to a better solution.

  Confrontational tendencies are not generally correlated with
  emotional expressiveness. For instance, Germans are usually not very
  expressive emotionally but do believe in vigorous debate.

  In confrontational disagreements, it is generally understood that
  the criticism is of the work product to make it better and not of the
  person in charge of the work product. In cultures that emphasize
  harmony, there may be a difference between an in-group and an
  out-group. A Chinese professional may not criticize people from his
  or her company to save face but may challenge everything from a
  supplier.
