#+TITLE: Early automotive industry - US in the early 1900s
#+FILETAGS: :automotive:
#+STARTUP: content, hideallblocks

* Henry Leland
:PROPERTIES:
:ID:       340ac842-915c-4131-8a51-1dafd44ff064
:END:

Leland was described as a master of perfection. He and his son,
Wilfred, helped build up the Cadillac Motor Company. Initially, his
company, was a supplier to Cadillac. However, when Cadillac was in
financial trouble, its board acknowledge the Lelands' manufacturing
expertise and asked them to run manufacturing for Cadillac.

The Lelands were deeply religious and followed the Protestant
faith. Henry did not drink or smoke. He had a fierce sense of duty
that trumped everything else.

Under Henry Leland's supervision, Cadillac pioneered the use of
electric self-starters in 1912 and the V8 engine in 1913. Charles
Kettering was instrumental in designing the electric self-starter. He
leveraged his experience from similar technology in cash registers at
NCR.

When World War I broke out, Henry felt it was his mission to help the
war effort. Airplane engines were being hand-manufactured in Europe at
the time and the concepts of mass manufacturing could be applied to
increase their yield. Henry asked Durant if a new plant that Cadillac
had just purchased could be used for manufacturing airplane
engines. Durant refused upon which Henry and his son quit the company
and decided to form their own company to manufacture airplane
engines. This new company was named the Lincoln Motor Company from
Leland's early days in the Springfield Armory building rifles for the
Civil War.

The Lincoln Motor Company took on a lot of debt from the US government
during World War I days. This resulted in a lot of controversy after
the war with the US Treasury issuing claims on tax evasion several
times. It was over-extended on debt during the recession of the early
1920s. As a result, it was under receivership. Leland's son, Wilfred,
worked hard to get Henry Ford to intervene and buy the company. In the
process, the Lelands lost their management roles in the company.

Henry Leland died soon after, at the age of 89.

* References

** Wilfred Leland, "Master of Perfection: Henry M Leland".
