#+TITLE: Early automotive industry - US in the early 1900s
#+FILETAGS: :automotive:
#+STARTUP: content, hideallblocks

* Henry Leland
:PROPERTIES:
:ID:       340ac842-915c-4131-8a51-1dafd44ff064
:END:

Leland was described as a master of perfection. He and his son,
Wilfred, helped build up the Cadillac Motor Company. Initially, his
company, was a supplier to Cadillac. However, when Cadillac was in
financial trouble, its board acknowledge the Lelands' manufacturing
expertise and asked them to run manufacturing for Cadillac.

The Lelands were deeply religious following the Protestant
faith. Henry did not drink or smoke.

When World War I broke out, Henry felt it was his mission to help the
war effort. Airplane engines were being hand-manufactured in Europe at
the time and the concepts of mass manufacturing could be applied to
increase their yield. Henry asked Durant if a new plant that Cadillac
had just purchased could be used for manufacturing airplane
engines. Durant refused upon which Henry and his son quit the company
and decided to form their own company to manufacture airplane
engines. This new company was named the Lincoln Motor Company from
Leland's early days in the Springfield Armory building rifles for the
Civil War.

* References

** Wilfred Leland, "Master of Perfection: Henry M Leland".
