#+TITLE: Books and notes on ethical thinking
#+FILETAGS: :Ethics:
#+STARTUP: overview

* Practical Ethics by Peter Singer                                   :Review:

Preference utilitarianism says that, if a person has a preference,
then that preference should not be tampered with, all other things
being equal. All people have a preference to stay alive, desires that
they want to fulfill etc. So, killing them is not acceptable.

We can assume such preferences exist for beings that are aware of
themselves and have an image of themselves in the past, present and
future. Note that, for instance, a fish doesn't necessarily have this
self-image. However, it may still struggle when it's about to
die. That is self-preservation which is separate from having a
self-image in the future.

For self-aware beings with a sense of past, present and future and a
set of preferences, it may not be ok to kill such a person even if you
introduce a new person with preferences. On the other hand, for a
being with no sense of time and self-image, it may be OK to kill such
a person if you substitute with another person who also has
preferences and if the killing can be done instantaneously without
suffering.

This raises the question of when it is OK to kill a person. If the person
has explicitly declared that they would like to be killed, then
euthanasia should be allowed based on preference utilitarianism. It
should also be allowed based on other philosophical models like rights
(the living person has a right to life and an option to give up that
right). This is voluntary euthanasia.

If the person has not requested death but it is clear that they will
face intense and irredeemable pain and suffering, then euthanasia
should be ethical if the person who administers it has done a
probabilistic calculation that leads to this conclusion. On the flip
side, it is unethical to let such a person die passively (through
non-intervention) if that causes significant suffering. Just as, if a
dog is in distress, we may take it to the vet to administer a lethal
injection, so also, if a baby suffers an incurable disease that is
guaranteed to cause lifelong suffering, it should be ethical to kill the
baby.

The one case in which this would be unethical is if the person had
expressed a desire to continue to live. In that case, that person's
preferences take precedence.

Contrary to popular opinion, a human life may not always be worth
living.

John Locke and Robert Nozick argue from a theory of rights ie the
right against interference. By their argument, everyone has a right
against interference from others but not a right to assistance from
others. However, this may not hold due to problems like buying
resources from despots, global warming, and purchasing products the
manufacture of which causes suffering to others.

* Vegetarianism                                                      :Review:

The meat industry causes suffering to and kills 74B animals every year.

If animal lives are even 1% as important as human lives, that's like
killing 740M humans a year. If we are 1% sure that those animals can
sense suffering, then also it is equivalent to killing 740M humans a
year. All this suffering is in aid of a discretionary interest that we
can do without, ie. eating animal flesh.

If you hear about a disaster that killed five people, you feel sorry
about that. If you hear about one that killed five thousand people,
you don’t feel a thousand times as sorry. Our feelings follow an
S-curve in that respect.

Stealing is disapproved of in our society, and we have internalized
that. Meat-eating is aproved of, and almost everyone around us is doing
it. That’s why we keep eating meat, no matter how wrong it
is. However, we won’t steal, no matter how much it would benefit us.

For most of the wrongs of the past – slavery, colonialism, the
oppression of women – the victims could and did speak up. In the case
of eating meat, the victims will never be able to act or speak for
themselves. There is no one to speak against what we humans are doing,
except us. So we have to do it. If we don’t, it will never stop.

** References

- Michael Huemer, "Dialogues on Ethical Vegetarianism"

* The Life you can save by Peter Singer                              :Review:

10% of the world's population lives in extreme poverty (< $2/day) as
of 2015. 85% lives on $30 or less per day.

If you can reduce the suffering of one other person without much
suffering for yourself, you should do so. Giving aid to charitable
organizations that work with poor people will help alleviate their
suffering. So, you must give as much money as you can spare to such
organizations. Anything less can be considered unethical.

In FY19, [[https://explorer.usaid.gov/][US foreign aid]] was $49B and US GDP was $2T. So, foreign aid
was roughly 2.5% of GDP.  The US is one of the highest contributors of
donations in absolute numbers but it is one of the lowest contributors
as a percentage of GDP or income. A lot of this aid goes to countries
that the US has political interests in and are not the poorest
countries in the world. A large part of the poorest people in the
world live in South Asia and in sub-Saharan Africa. Our charitable
donations should go to them.

A donation of $50 can help with avoidable problems like cataracts. A
donation of $3000 san save a life in a poor country. A donation of
$2/year can bring chlorinated water to one poor person. In contrast,
the cost of saving a life in the US is estimated at $2M.

According to [[https://givingusa.org/giving-usa-2020-charitable-giving-showed-solid-growth-climbing-to-449-64-billion-in-2019-one-of-the-highest-years-for-giving-on-record/][Giving USA]], in 2020, private donors (individuals,
foundations, companies) in the US gave $470B in charity. Out of that,
giving to international affairs was about $20B. That amounts to about
$1600/year of total charity per person and $70/year of international
charity. People generally prefer to give to causes that are dear to
their heart and not necessarily to causes that bring the most value.

A [[https://howrichami.givingwhatwecan.org/how-rich-am-i?income=200000&countryCode=USA&household%5Badults%5D=2&household%5Bchildren%5D=2][US household income]] of $200k for a family of four can put you in the
top 1% of the world. Donating 10% of your income still keeps you in
the top 1% and potentially saves about 20 human lives/year.

People in rich countries are already doing harm to those in poor
countries eg through global warming, buying goods from companies that
bribe officials to gain resources from poor countries, blocking
immigration and trade from other countries etc. The US subsidizes its
own farmers and applies tariffs on imports from other countries, thus
making it harder for farmers from poor countries to sell their goods
here.

Generally speaking, you should not give money to poor people directly
because it may cause dependence. Instead, money should be spent on
organizations that provide healthcare, education, housing etc.

People do things based on what other people in their peer group are
doing. So, if you're doing something moral like going vegetarian or
donating a large part of your income to charity, you should announce
it publicly and talk about it so that your peers are induced to do the
same.

People already show altruism in some forms eg leaving tips in
restaurants that they may never go back to. However, more altruism
needs to be directed to the world's poorest people.

Warren Buffett donated a large part of his income after he became a
billionaire. It would have been a mistake if he had donated the first
million he made because then he wouldn't be able to donate billions in
later life. However, not all of us are expert investors like
Buffett. Most of us should donate money now rather than later, because
the benefit of a lesser sum now outweighs the benefit of a slightly
larger sum later.

Instead of giving a small amount of charity and using the rest of the
money for discretionary expenses, we should be cutting out many
discretionary expenses and giving more to charity.

There are many reasons why it is not in human nature to give to poor
people on the other side of the world: no identifiable victim,
parochialism in generosity, illusion of futility, notion of fairness,
distributed responsibility, etc.

Economists like William Easterly have argued that giving aid can be
a wasteful effort. However, this is usually concerned with large
donors such as governments, World Bank etc. An individual or a
group's donations are unlikely to be affected by this. However,
individuals should try to find the best use of their money through
reasonable study.

Moral consequentialist theory may suggest that you should save a
reasonable amount for your discretionary expenses and donate
everything else. However, in the real world, people seldom implement
such extreme measures. So, advocating for such extreme measures are
unlikely to succeed. Further, this may not hold true in the
deontological view.

Even donating 5-10% of your net income and spreading the word to
others can make a significant difference. There is higher chance of
adoption of this level too.

** My donations
:PROPERTIES:
:CUSTOM_ID: my_donations
:ID:       7d940e83-ba83-4650-9076-797cc3271ca6
:END:

By the argument above, a donation of $5000 in 2025 can save a life
in a poor country which can be valued at, say, $100,000. $100k is a
pretty conservative estimate of the lifetime value of a human
being. Thus, an investment of $5000 today generates a lifetime
revenue of $100,000. Let us assume that the investment is made in a
newborn baby. Let us assume that this person generates no income for
20 years and then generates $2.5k/year for 40 years. By this scheme,
the NPV to that person is about $16k at a market rate of 5%.

Thus, for my donations, I can assume 16k/5k or a multiplier of 3
for value. This assumes no employer matching.

* Effective Altruism                                                 :Review:

Ajeya Cotra has a heart-felt introduction to [[https://forum.effectivealtruism.org/s/YCa8BRQoxKbmf5CJb/p/5EqJozsDdHcF7dpPL][effective altruism]].

** Why you should maximize your impact

The average doctor in the UK may add about 150 healthy
years over their career. The World Bank has a conversion rate of one
life for every 30 healthy years, so a doctor in a developed country
can save about 5 human lives over the course of their career.

Some doctors have had 100,000 times that much impact in their lives
e.g. the doctors who helped eradicate small-pox. Similarly, the Soviet
bureaucrat [[http://www.bbc.com/news/world-europe-24280831][Stanislav Petrov]] may have saved a billion lives by refusing
to launch nuclear missiles according to protocol. Some of this was
luck but, by making choices of which areas you focus on, you can get
100-1000 times the impact of an average person in your field.

You can [[https://forum.effectivealtruism.org/s/YCa8BRQoxKbmf5CJb/p/hk9Xh6xK5j3SQmkcn][increase your benefit to society]] in one of three ways.
  - Helping more people
  - Helping the same number of people to a greater extent, or
  - Doing something which has benefits that last for a longer time.

* The world is much better and can be much better

All three of the following are true.
  - The world is much better than before
  - The world is awful
  - The world can be much better than it is right now

However, according to the [[http://www.fao.org/3/ca9692en/online/ca9692en.html#][State of Food Security report]] in 2020,
the number of undernourished has been going up since 2014. In 2020,
nearly 700 million people or about 9% of the world population
were hungry. This number has been increasing since 2014 and COVID
has the potential to make the trend worse. Most of the world's
hungry population are in Asia and Africa.

5 million children or 3.6% of the world population died before
reaching the age of 5 in 2023. These numbers were 17 million and 13.7%
respectively 50 years ago. Thus, the numbers have gone down
significantly both in absolute and fractional terms. However, 5
million children dying every year is still a profound tragedy that
deserves attention..

* Political authority                                                :Review:

Moral consequentialism: you should only take an action if, in doing
so, the total benefit to society is positive. For instance, the
argument against a person not voting is that, if everyone did that,
there would be no voting and government would collapse. The
counterargument is that your moral rule is to not vote, when there are
enough other people voting already so that your not voting does not
affect the results much.

For example, if you are on a lifeboat that takes in water and three
other people are already bailing out water, then it might not make
much sense for you to bail out water too. It is better for you to
spend the time on some other useful activity.

We tend to see the beliefs of our own society as obviously true.

Governments use many aesthetic elements to convey a sense of power eg
state buildings have large columns, are built on top of hills, have
statues of soldiers and cannons to remind visitors of the state's
military might.

Court proceedings are exceedingly formal, perhaps because it is here
that the image of justice through coercion has to be reinforced.

Just as kidnap victims may develop an affinity for their captors
through Stockholm syndrome, so also citizens of a state may develop an
affinity for their government since the government has complete
control over them. All the conditions that lead to Stockholm syndrome
may apply in the interaction of an individual with a state too.

Stanford experiment by Philip Zombardo: people randomly assigned to be
guards and prisoners. Guards started abusing their power quickly,
making prisoners do tedious non-constructive work, hurling verbal
abuse etc. Even though some guards had reservations, they did not do
anything to stop the abusive guards. Prisoners obeyed the guards even
though they outnumbered them and the guards did not have any means to
enforce authority.

Why do so many individuals believe in the power of the state? Perhaps
because human beings may be wired to accept authority figures even
when that authority is illegitimate.

We are morally obligated to disobey an unjust law. However, we are not
morally obligated to undergo the punishment that the state may enforce
for breaking that law.

Large failures of government tend to get rewarded rather than
punished. For example, after 9/11, the approval ratings of the Bush
government improved significantly. This may be partly because people
confuse the nation with its government and, hence, a patriotic feeling
gets converted to an approval of the government. It may partly be due
to the fact that systemic failures are hard to understand and people
tend to ascribe easier ideas like lack of funding to failures and
argue for more funding when there is any problem.

Two factors distinguish any state service:
Monopoly - no other agent can provide that service
Coercion - the state can coerce you to accept the service

In the US, two thirds of prisoners go back to prison within three
years. Recidivism rates are very high.

** References

- Michael Huemer, The Problem of Political Authority

* Poor Economics by Abhijit Banerjee and Esther Duflo                :Review:

Poor people don't generally want more food. In many cases, giving them
grain etc is not helpful. Instead, providing more micronutrients,
iron, iodine etc may be more helpful.

Immunization is often not successful. This may be because poor people
don't easily see the benefits of long term interventions like
immunization. They may also distinguish between diseases that they use
traditional healing versus ones for which they see a doctor. However,
sometimes these beliefs are not strongly held. A little incentive
(some dal for each immunization and a set of stainless steel plates to
complete the course) can overcome it.

We naturally tend to postpone small costs and discount the benefits
that may accrue from them. The reverse holds for rewards. This is
called time inconsistency. Small incentives like the one above can
compensate for time inconsistency effects. While such nudges sound
paternalistic, the truth is that even citizens in developed countries
need such nudges and take them for granted. For instance, we get our
kids vaccinated because, if not, schools won't accept them. We go to
gyms partly because our insurance subsidizes it.

Although poor people could generally benefit from risk insurance, they
generally don't buy it. Some of this may be due to the nature of the
product (you pay for something that you hope you never use). Trust in
the insurance agent may also be a factor.

Microfinance institutions work reasonably well but they have not proven to be
transformative. They rely on strict loan repayment rules and usually
lend to a group of people. The group ensures through social pressure
that everyone in the group makes payments on time. Due to these strict
rules, it's harder for example to borrow for health related
emergencies where people may not be able to pay back
immediately. Moneylenders continue to operate and charge much higher
interests even in areas where such institutions are active.
