#+Title: Articles on EV charging stations and market trends
#+FILETAGS: :Charging:Review:
#+STARTUP: content


* Charging companies


** Chargepoint
:PROPERTIES:
:ID:       e188834e-94ce-44a8-9ff2-3a99c8096ffe
:END:

  Chargepoint has about 350k connectors in the US and Europe combined.

  Chargepoint made revenue of $361M in [[https://investors.chargepoint.com/news/news-details/2024/ChargePoint-Reports-Fourth-Quarter-and-Full-Fiscal-Year-2024-Financial-Results/default.aspx][FY 2024]] with a net loss of $458M.


** EVGo
:PROPERTIES:
:ID:       326fe6de-1cb4-476a-bee0-0583f2c203f9
:END:

  As of Apr-2025, EVGo has 1100 DCFCs in the US.

  EVGo made revenue of $256M in [[https://investors.evgo.com/news/news-details/2025/EVgo-Inc.-Reports-Record-Fourth-Quarter-2024-Results/default.aspx][FY 2024]] with a net loss of $127M or 50%.

  AutoCharge+ accounted for 25% of charging sessions in Q4 2024.


* EV charging station trends
:PROPERTIES:
:ID:       9f94c234-8138-48c1-9e67-7a97a066d91c
:END:


|-----------+------------------------------------+------------------------------|
| Date      | Number of public L2 chargers in US | Number of public DCFCs in US |
|-----------+------------------------------------+------------------------------|
| 01-Dec-24 | 60,000                             | 12,000                       |
| 27-Jun-25 | 62,500                             | 12,800                       |
|-----------+------------------------------------+------------------------------|

  Source: [[https://afdc.energy.gov/stations#/find/nearest?fuel=ELEC][DoE site]]

  Growth in the first 6 months of 2025 was roughly 8% annualized for
  L2 chargers and 14% annualized for DCFCs.

  There's a discrepancy between this data and the IEA data that shows
  100k public slow chargers in the US. Perhaps, the DoE count is less
  because it only counts live chargers.


* EV charging

  A standard AC socket in the US (120 V, 15 A) can give about 1.8 kW of
  power. A Level 2 charger (240 V, 30 A) can provide about 7.2 kW of
  power.

  DC fast chargers (Level 3) can provide up to 150 kW of power. For a
  70 kWh battery, that implies full charge in about 30 min. The same
  full charge would take 10 hours on a level 2 charger.

  An average US home consumes about 1 kW of power, so a DC fast
  charger is equivalent to about 150 homes at its peak charging. Even
  a level 2 charger is equivalent to about 7 US homes.


* Tasks

** TODO Update [[id:9f94c234-8138-48c1-9e67-7a97a066d91c][table]] with latest information on charging sites in the US :Browser:Home:
SCHEDULED: <2025-09-15 Mon +12w>
:PROPERTIES:
:EFFORT:  00:15
:BENEFIT: 10
:RATIO: 0.40
:END:


** TODO Update [[id:e188834e-94ce-44a8-9ff2-3a99c8096ffe][Chargepoint]] and [[id:326fe6de-1cb4-476a-bee0-0583f2c203f9][EVGo]] earnings for the quarter   :Browser:Home:
SCHEDULED: <2025-07-15 Tue +12w>
:PROPERTIES:
:EFFORT:  00:15
:BENEFIT: 10
:RATIO: 0.40
:END:
