#+Title: Articles on EV charging stations and market trends
#+FILETAGS: :Charging:Review:
#+STARTUP: content

* Charging companies



** Chargepoint
:PROPERTIES:
:ID:       e188834e-94ce-44a8-9ff2-3a99c8096ffe
:END:

  In [[https://investors.chargepoint.com/news/news-details/2025/ChargePoint-Reports-First-Quarter-Fiscal-Year-2026-Financial-Results/default.aspx][Q1 FY26]] (ending April 30th 2025), total revenue was $98M down 9%
  y-o-y. GAAP net loss was $57M down 20% y-o-y.

  Chargepoint made revenue of $361M in [[https://investors.chargepoint.com/news/news-details/2024/ChargePoint-Reports-Fourth-Quarter-and-Full-Fiscal-Year-2024-Financial-Results/default.aspx][FY 2024]] with a net loss of $458M.


** EVGo
:PROPERTIES:
:ID:       326fe6de-1cb4-476a-bee0-0583f2c203f9
:END:

  In [[https://investors.evgo.com/news/news-details/2025/EVgo-Inc--Reports-Record-First-Quarter-2025-Results/default.aspx][Q1 FY25]], revenue was $75M with net loss of $11M.

  As of Apr-2025, EVGo has 1100 DCFCs in the US (roughly 11% of the US
  market).

  EVGo made revenue of $256M in [[https://investors.evgo.com/news/news-details/2025/EVgo-Inc.-Reports-Record-Fourth-Quarter-2024-Results/default.aspx][FY 2024]] with a net loss of $127M or 50%.

  AutoCharge+ accounted for 25% of charging sessions in Q4 2024.


* EV charging stations in the US
:PROPERTIES:
:ID:       9f94c234-8138-48c1-9e67-7a97a066d91c
:END:


** Growth trend for US charging stations

The following table shows the number of public L2 and DCFC charging
stations in the US.

|-----------+--------+--------|
| Date      | L2     | DCFC   |
|-----------+--------+--------|
| 01-Dec-24 | 60,000 | 12,000 |
| 27-Jun-25 | 62,500 | 12,800 |
|-----------+--------+--------|

Source: [[https://afdc.energy.gov/stations#/find/nearest?fuel=ELEC][DoE site]]

Growth in the first 6 months of 2025 was roughly 8% annualized for L2
chargers and 14% annualized for DCFCs.

** Growth trend for ports
:PROPERTIES:
:ID:       155a9380-eb88-4b00-9365-15511ce0c60f
:END:

The following data is for L2 and DCFC ports.

|------+-----------------+---------------+--------------------+------------|
| Year | L2 Ports (est.) | DC Fast Ports | Total Public Ports | YoY Growth |
|------+-----------------+---------------+--------------------+------------|
| 2025 | 145,000         | 49,916        | 195,874            |      10.5% |
| 2024 | 133,750         | 43,500        | 177,250            |            |
| 2021 |  91,000         | 21,700        | 112,700            |            |
| 2020 |                 |               |  96,536            |            |
| 2016 |  30,000         |               |  30,000            |            |
|------+-----------------+---------------+--------------------+------------|

Source: [[https://chatgpt.com/share/685fd64f-c558-800b-ab0a-284e761978f1][ChatGPT on 28-Jun-25]] and [[https://www.rabobank.com/knowledge/d011438559-the-rise-of-electric-vehicles-in-the-us-building-a-robust-charging-network?utm_source=chatgpt.com][Rabobank research]]


From [[https://www.eia.gov/totalenergy/data/monthly/pdf/mer_F_FULL.pdf?utm_source=chatgpt.com][AFDC-based data]], at the end of June 2025, there were about 60k
DCFC ports and 180k L2 ports. These are a combination of public and
private (although the private count excludes single-home chargers).

The total is about 240k out of which about 72k are at public locations
and 3.6k at private locations. So, we can assume that 3.6/(72+3.6) or about 5% of
all ports are private. Multiplying the numbers above by 95%, we get
the estimated number of DCFC ports to be about 60k*0.95 = 57k and the
estimated number of L2 ports to be about 180k*0.95 = 171k.

At the end of 2023, the numbers were 40695*(63069/(63069+3106)) = 39k DCFC
ports and 161534*(63069/(63069+3106)) = 154k L2 ports.

At the end of 2024, the numbers were 52539*(69616/(69616+3546)) = 50k DCFC
ports and 172220*(69616/(69616+3546)) = 164k L2 ports.

This gives a growth of (50-39)/39 = 28% in DCFC ports and
(164-154)/154 = 6.5% in L2 ports in 2024. The total port growth was
(214-193)/193 = 11% in 2024.

That gives a growth of (57-50)/50 = 14% in DCFC ports and
(171-164)/164 = 4% in L2 ports in the first half of 2025. The total
port growth was (228 - 214)/214 = 6.5% in the first half of 2025.


*** TODO Look at [[https://www.eia.gov/totalenergy/data/monthly/pdf/mer_F_FULL.pdf?utm_source=chatgpt.com][AFDC-based data]] and update this table         :Browser:Work:
:PROPERTIES:
:EFFORT:  00:15
:BENEFIT: 10
:RATIO: 0.40
:END:


** Composition by CPO

The composition of ports in 2024 is as follows.

|---------------------------+----------+---------------+------------+-----------------|
| Operator                  | L2 Ports | % of L2 Ports | DCFC Ports | % of DCFC Ports |
|---------------------------+----------+---------------+------------+-----------------|
| ChargePoint               |   45,000 |          ~33% | ~3,946     | ~8%             |
| Tesla Supercharger        |        0 |            0% | ~30,767    | ~60%            |
| Electrify America         |      100 |           <1% | ~4,799     | ~9%             |
| EVgo                      |      200 |           <1% | ~3,989     | ~8%             |
| Blink                     |    3,500 |           ~3% | ~175       | ~<1%            |
| Volta (Shell-owned)       |    2,000 |         ~1.5% | 0          | 0%              |
| Shell Recharge (ex-Volta) |    1,000 |         ~0.7% | ~550       | ~1%             |
| Rivian Waypoints (L2)     |      375 |           <1% | 0          | 0%              |
| Rivian Adventure (DCFC)   |        0 |            0% | ~385       | <1%             |
| Others                    |   82,825 |          ~61% | ~7299      | ~12%            |
|---------------------------+----------+---------------+------------+-----------------|
| Total (estimate)          |   135000 |          100% | ~51,500    | 100%            |
|---------------------------+----------+---------------+------------+-----------------|

ChargePoint leads the US market in L2 with 33% and Tesla in DCFC with 60%.

Source: [[https://chatgpt.com/share/685fd64f-c558-800b-ab0a-284e761978f1][ChatGPT on 28-Jun-25]] and [[https://www.rabobank.com/knowledge/d011438559-the-rise-of-electric-vehicles-in-the-us-building-a-robust-charging-network?utm_source=chatgpt.com][Rabobank research]]


* Power ratings for charging
:PROPERTIES:
:ID:       f652f1ee-71e3-4455-93bc-c090ab71254c
:END:

  A standard AC socket in the US (120 V, 15 A) can give about 1.8 kW of
  power. A Level 2 charger (240 V, 30 A) can provide about 7.2 kW of
  power.

  DC fast chargers (Level 3) can provide up to 150 kW of power. For a
  70 kWh battery, that implies full charge in about 30 min. The same
  full charge would take 10 hours on a level 2 charger.

  A DC fast charger is equivalent to about 150 US homes at its peak charging. Even
  a level 2 charger is equivalent to about 7 US homes.


* Power consumption of an average US home
:PROPERTIES:
:ID:       d51a7c0d-0649-40cf-b9fb-29e759f4ea6a
:END:

  An average US home consumes about 1 kW of power. Since a year has
  about 9000 hours, that translates to 9 MWh/year of consumption.



* Tasks


** TODO Update [[id:9f94c234-8138-48c1-9e67-7a97a066d91c][table]] with latest information on charging sites in the US :Browser:Home:
SCHEDULED: <2025-09-15 Mon +12w>
:PROPERTIES:
:EFFORT:  00:15
:BENEFIT: 10
:RATIO: 0.40
:END:


** TODO Update [[id:e188834e-94ce-44a8-9ff2-3a99c8096ffe][Chargepoint]] and [[id:326fe6de-1cb4-476a-bee0-0583f2c203f9][EVGo]] earnings for the quarter   :Browser:Home:
SCHEDULED: <2025-10-07 Tue +12w>
:PROPERTIES:
:EFFORT:  00:15
:BENEFIT: 10
:RATIO: 0.40
:LAST_REPEAT: [2025-07-16 Wed 12:30]
:END:
- State "DONE"       from "TODO"       [2025-07-16 Wed 12:30]
