#+TITLE: An introduction to game theory by Steven Tadelis
#+FILETAGS: :economics:games:mathematics:probability:BookNotes:
#+STARTUP: content

* Three factors to making a decision                                 :Review:

  - Actions
  - Outcomes that result from each action
  - Utility/preference for each outcome

  A rational choice is one in which the agent chooses an action that
  maximizes the expected utility. Actions can result in outcomes with
  certain probabilities. This is a consistent and analyzable
  approach. However, many practical situations are multi-player games
  e.g. how you do on a course depends not just on how much time you
  spend studying for it but also on how much effort other students
  spend on the course. Thus, decision theory quickly translates into
  multi-player games.

  Probabilistic outcome games can be interpreted as two-party games
  between an agent and Nature. For instance, in a game based on coin
  flips, Nature first decides (with equal probability) whether the
  coin flip will result in a Heads or a Tails. Based on the outcome,
  the player may then have a strategy which results in certain
  outcomes.


* Static games of complete information                               :Review:

  1. Each player simultaneously and independently chooses an action.
  2. Based on the chosen actions, each player gets a payoff/utility
     (could be deterministic or probabilistic).
  3. All players understand the parameters of the game they are playing.

  Item 3 is an assumption of "common knowledge" i.e. all players know
  E, everyone knows that everyone knows E, etc. ad infinitum. This is
  a strong assumption. For instance, if a student heard the professor
  say that there is a test the next day, he can not be sure that
  another student wasn't asleep and missed that announcement.


* Normal-form game                                                   :Review:

   In this form of game, the players are assumed to have no
   information about the moves of the other players. This may either
   be because all players move at the same time (like Rock, Paper,
   Scissors) or because the information of a player's move isn't
   available in time for the other player to make her move.

   The normal-form game consists of three components:
   - A finite set of players
   - A collection of sets of pure strategies ${S_1, S_2,\ldots, S_n}$
   - A set of payoff functions ${v_1, v_2, \ldots, v_n}$, each of
     which assigns a payoff to a combination of chosen strategies.

   "Pure strategy" implies that the strategy is not random. "Mixed
   strategy" implies that choices can be made randomly between pure
   strategies.


* Dominant strategy and Nash equilibrium                             :Review:

  A dominant strategy is one in which a player has a strategic choice
  and no other strategy for the player results in a better payoff,
  irrespective of the other players' strategies.

  A Nash equilibrium (NE) is a set of strategies for the players such
  that the NE strategy for each player is the best response to the NE
  strategies of all the other players. A dominant strategy is an NE
  but not vice versa.

  The attraction of the NE is that it can be proven to exist under
  fairly general conditions of finite normal-form games if you allow
  mixed strategies (see section below). However, even though an NE may
  exist, it may not be easily computable.


* Prisoner's dilemma                                                 :Review:

   In a prisoner's dilemma problem, each prisoner
   can either "fink" (F) or remain "mum" (M). The payoff matrix is as
   follows (where the lower case and upper case distinguish each
   player's move).

   |--------------------+----------+----------|
   | Player 1/Player 2  | m        | f        |
   |--------------------+----------+----------|
   | M                  | (-2, -2) | (-5, -1) |
   | F                  | (-1, -5) | (-4, -4) |
   |--------------------+----------+----------|

   In the payoff matrix, for each column (strategy for player 2), F has
   the higher payoff for player 1. Similarly, for each row (strategy
   for player 1), f has the higher payoff for player 2. Hence, (F, f)
   is dominant and, by definition, also an NE.

   This is a disturbing result since, although both players could land
   on a "better" outcome of (M, m), they will rationally end up
   choosing (F, f).


* Mixed strategies                                                   :Review:

  A mixed strategy is where a player may choose from any of a finite
  set of strategies with a certain probability. This can also be
  considered as a "belief" of a player about the other player's
  strategy. For example, player i may not know what player j may play
  but may have certain beliefs about the strategies of player j and
  may choose her best move according to those beliefs.

  Choosing mixed strategies can result in NEs in games
  where fixed strategies don't do so. Thus, it provides a richer tool
  set for playing games.

  If there is a mixed strategy that is a Nash
  equilibrium, it must be a convex combination of strategies that have
  the same utility against the best response strategy of the other
  players.


* Extensive-form game                                                :Review:

  This is an extension of the normal-form game where there is a
  sequence of moves for the players and the players may get information
  about what moves the players before them made. Further, it is
  assumed that this extensive-form structure is common knowledge for
  all players.

  In some cases, the analysis here can be simplified by considering
  game sub-trees and applying sequential rationality.

  An interesting example of this is the war game simulation of the
  Cuban missile crisis. In one version of this game, the Nash
  equilibria lie outside the mutual destruction path but the existence
  of the mutual destruction path is enough for rational players to
  take steps to avoid it.


* Multi-stage games                                                  :Review:

  In the normal-form and extended-form games, the payoff was received
  by all players at the end of their moves. We can now extend this
  analysis to sequences of either the same or different games with
  payoffs received at the end of each game occurrence. In such cases,
  discounting future payoffs is necessary so that rational players can
  make choices about which strategies to choose in early games to
  account for gains in later games.

  For example, we can consider a multi-stage game that consists of the
  Prisoner's dilemma followed by revenge consisting of the prisoners
  potentially joining gangs and taking revenge on each other. If the
  two prisoners stay mum in the first game, there is a higher chance
  that they will stay a loner in the second game and not join a
  gang. This "carrot-and-stick" option in the second game can be
  enough to force the (M, m) option in the first game although it's
  not a NE for that game by itself. In order for this to
  work, the incentives and discounting factors have to be
  correctly designed.

  Note that the choice of a non-NE in an early stage
  game can only be enforced if two conditions are met:
  - There are multiple NEs in later stage games
  - Players can be "patient" i.e. discount factors are high enough.

  If the first factor does not hold, it is rational to play the NE in
  each game and those NEs are known in advance. If the second factor
  does not hold, there isn't enough of a carrot to deviate from the NE
  in the early rounds.

  In order to find the NE for a multi-stage game, you do
  not need to consider exponentially many possibilities based on the
  equilibria for each stage. The method of dynamic programming can be
  used with backward induction to calculate the equilibrium strategy
  working backwards.

  As a direct consequence of the above, if the Prisoner's dilemma game
  is played a finite number of times, the NE is to fink
  in each game. However, if there are either an infinite number of
  games with discounted payoff or if the players may or may not play
  the next iteration of the game with some probability, then things
  get more interesting.

  In this case, the "Always fink" strategy is, of course, an
  NE. However, other strategies like "Grim trigger" strategies can
  also be NEs for high values of the discount (or probability of next
  play). A grim trigger strategy is one where each player will play
  M/m as long as the previous play history up to that point does not
  include a single F/f.

  In general, if there are infinite plays, then you can get
  arbitrarily close to any legitimate payoff of a single-stage version
  of the game as long as you are allowed to make the discount factor
  arbitrarily close to 1.


* Auctions                                                           :Review:

  Auctions can be of either the private values or the common values
  types. In private value auctions, each player assigns a value to the
  auction and the payoff to the player is dependent only upon the
  player's private value e.g. if you buy something to eat or a work
  of art. In a common values auction, the payoff of each player
  depends not just upon that player's assigned value but also upon
  other players' values.

  In private value settings, the second-price
  sealed-bid auctions are equivalent to English
  auctions. Bidding your private value is weakly dominant. The
  first-price sealed-bid auctions are equivalent to Dutch auctions. In
  these cases, each player must "shade" their valuation when bidding
  to obtain a positive expected payoff and bidding your private
  valuation is not dominant any more.

  In common value settings, each player must account for the fact that
  they may win because the other player values the good lower. This is
  called "winner's curse".
