#+TITLE: Human progress
#+FILETAGS: :Society:
#+STARTUP: overview, hideallblocks

* Rationality                                                        :Review:

Maybe it is reasonable in the 21st century for human beings to be more
anxious than previous generations. Maybe, there are important problems
such as global warming, the potential for nuclear disaster, etc that
previous generations didn't face and that we should worry about and
address. However, it is also true that the world is a better place
than it has ever been.

This has primarily been due to the Enlightenment that turned away from
religion and towards humanism, reasoning, and problem-solving.

** Related links

- [[id:13537c7c-c8ea-4a29-819e-c49ee37b1130][The European Renaissance]]

* Humanism                                                           :Review:
:PROPERTIES:
:ID:       1a57ed2c-9a0e-479e-a5fe-377219d090ea
:END:

The American Humanist Association defines Humanism as follows.

"Humanism is a progressive philosophy of life that, without theism or
other supernatural beliefs, affirms our ability and responsibility to
lead ethical lives of personal fulfillment that aspire to the greater
good."

Their motto is "Good without a God".

See also [[id:16405c0a-2d59-421b-acf4-8f06b9a59a62][Poetic naturalism]].

** References

- Steven Pinker, Enlightenment now.
