#+TITLE: An introduction to game theory by Steven Tadelis
#+FILETAGS: :economics:games:mathematics:probability:Books:Learning:

* Three factors to making a choice or a decision

  - Actions
  - Outcomes that result from each action
  - Utility/preference for each outcome

  A rational choice is one in which the agent chooses an action that
  maximizes the expected utility. Actions can result in outcomes with
  certain probabilities. This is a consistent and analyzable
  approach. However, many practical situations are multi-player games
  e.g. how you do on a course depends not just on how much time you
  spend studying for it but also on how much effort other students
  spend on the course. Thus, decision theory quickly translates into
  multi-player games.

  Probabilistic outcome games can
  be interpreted as two-party games between an agent and Nature. For
  instance, in a game based on coin flips, Nature first decides (with
  equal probability) whether the coin flip will result in a Heads or a
  Tails. Based on the outcome, the player may then have a strategy
  which results in certain outcomes.


* Static games of complete information

  1. Each player simultaneously and independently chooses an action.
  2. Based on the chosen actions, each player gets a payoff/utility
     (could be deterministic or probabilistic).
  3. All players understand the parameters of the game they are playing.

  Item 3 is an assumption of "common knowledge" i.e. all players know
  E, everyone knows that everyone knows E, etc. ad infinitum. This is
  a strong assumption. For instance, if a student heard the professor
  say that there is a test the next day, he can not be sure that
  another student wasn't asleep and missed that announcement.


* Normal-form game

   In this form of game, the players are assumed to have no
   information about the moves of the other players. This may either
   be because all players move at the same time (like Rock, Paper,
   Scissors) or because the information of a player's move isn't
   available in time for the other player to make her move.

   This consists of three components:
   - A finite set of players
   - A collection of sets of pure strategies ${S_1, S_2,\ldots, S_n}$
   - A set of payoff functions ${v_1, v_2, \ldots, v_n}$, each of
     which assigns a payoff to a combination of chosen strategies.

   "Pure strategy" implies that the strategy is not random. "Mixed
   strategy" implies that choices can be made randomly between pure strategies.


* Dominant strategy and Nash equilibrium

  A dominant strategy is one in which a player has a
  strategic choice and no other strategy for the player results in a better payoff,
  irrespective of the other players' strategies.

  A Nash equilibrium is a set of strategies for each player such that
  the strategy for each player is the best response to the strategies
  of all the other players. A dominant strategy is a Nash
  equilibrium but not vice versa.


* Prisoner's dilemma

   For instance, in a prisoner's dilemma problem, each prisoner
   can either "fink" (F) or remain "mum" (M). The payoff matrix is as
   follows.

   |--------------------+----------+----------|
   | Player 1/Player 2  | M        | F        |
   |--------------------+----------+----------|
   | M                  | (-2, -2) | (-5, -1) |
   | F                  | (-1, -5) | (-4, -4) |
   |--------------------+----------+----------|

   In the payoff matrix, for each column (strategy for player 2), F has
   the higher payoff for player 1. Similarly, for each row (strategy
   for player 1), F has the higher payoff for player 2. Hence, (F, F)
   is dominant.

* Extensive-form game

  This is an extension of the normal-form game where there is a
  sequence of moves for the players and the players get information
  about what moves the players before them made. Further, it is
  assumed that this extensive-form structure is common knowledge for
  all players.
