#+TITLE: Software development practices
#+FILETAGS: :Software:
#+STARTUP: overview, hideallblocks

* Open source software foundations

** Mozilla Foundation

They govern Firefox and Thunderbird development.

** Cloud-Native Computing Foundation

** Apache Foundation

They govern Apache Spark and Apache Kafka, among other projects.

** Eclipse Foundation
:PROPERTIES:
:ID:       30978d6c-a649-4c4e-a4c1-3a124ca965e0
:END:

They govern Ecllipse ThreadX, the RTOS, and the Eclipse IDE, among
other projects.

See also [[id:59b8b305-3e77-403e-99d1-51d6eb2f4297][Eclipse ThreadX]].

** Linux Foundation

** Python Software Foundation

** Free Software Foundation

GNU, Emacs, etc.

* Optimization

[[https://en.wikipedia.org/wiki/Tony_Hoare][Tony Hoare]] said that "premature optimization is the root of all
evil." This quote, repeated by Donald Knuth, is often interpreted
to mean that you should never optimize your code or that you can
expect silicon improvements to get you efficiency faster than
developers can optimize code.

[[https://ubiquity.acm.org/article.cfm?id=1513451][Randall Hyde]] makes the case that all of
these are fallacies. He argues that developers must continue to focus on
optimization as part of the development cycle just as they focus on
architecture, design, and validation.

* Measuring developer productivity                                   :Review:
:PROPERTIES:
:ID:       aa3bd004-c924-46e4-939b-6820d173cde7
:END:

The company DX (to be acquired by Atlassian in 2025) has implemented a
developer score, DX Core 4, that allows organizations to measure and
optimize developer productivity. It uses four dimensions - speed,
effectiveness, quality, and impact.

** TODO Read [[https://getdx.com/research/measuring-developer-productivity-with-the-dx-core-4/][Measuring developer productivity with DX Core 4]]       :Learning:
:PROPERTIES:
:EFFORT:  00:15
:BENEFIT: 10
:RATIO: 0.40
:END:

** References

- DX, [[https://getdx.com/research/measuring-developer-productivity-with-the-dx-core-4/][Measuring developer productivity with DX Core 4]]
