#+TITLE: Books on US Civil Rights
#+FILETAGS: :BookNotes:
#+STARTUP: overview

* King by Jonathan Eig                                               :Review:

MLK had taken a job as a preacher in Montgomery, Alabama, just weeks before Rosa
Parks' boycott. He was still relatively unknown in the NAACP and other
circles while people like Rosa Parks were veteran organizers. However,
King was able to establish himself as the leader of the movement. He
was a charismatic leader and helped bring national attention to the
Montgomery boycott. In spite of all this, it took nearly one year of
boycott before the Supreme Court sided with the boycotters and
declared Montgomery's bus segregation unconstitutional.

King was not interested in the details of the organization of the
Southern Christian Leadership Conference (SCLC). As a result, the
organization suffered. He was also unwilling to hand over reins to the
woman who was the Executive Director.

The NAACP was more interested in legal action to fight the racism in
the south. After the bus boycott, the SCLC was struggling to keep the
momentum going. It was the students in Atlanta who got the momentum
going again with the lunch counter sit-ins.

Nixon could have helped MLK get out of jail but it was Kennedy who put
in the call. Black people were grateful to Kennedy for this action and
voted heavily for him in the election against Nixon. However, it is
also possible that southern whites voted against Kennedy as a result.

King was an idealist. He hadn't intended to become the leader of the
black movement. However, once the position was thrust upon him, he
refused to take the easy way out. He believed firmly that this was a
cause he was willing to die for and gave up money, safety, and comfort
for its sake.

J. Edgar Hoover was vehemently opposed to King and was sure that he
was a communist. Hoover placed a wire tap on King's home phone and
recorded all his conversations. Both the Kennedy brothers and Lyndon
Johnson authorized this wire tap and reviewed the reports. The FBI
also tried to plant these reports with journalists and asked them to
write stories about King.

In 1965, King organized protests in Chicago against the nature of
black housing. The protests resulted in no significant gains but
alienated a lot of white supporters who thought the movement should be
confined to the south.

King's stance against the Vietnam War further alienated some
supporters but he felt he had to take that stance out of his
principles. In 1968, he decided he would conduct a march of civil
disobedience in Washington to protest the war and the conditions of
the poor. The idea, like King's many protest ideas, was grand in
vision and sparse in detail. The specific demands were not clear and
it wasn't clear whether reasonable demands would be made. The risk of
it turning violent was also quite high. He lost confidence among many
supporters due to this.

The march was completed by Coretta Scott King after he died.


** MLK Jr: If we are wrong, justice is a lie. Love has no meaning. And we are determined to fight until justice runs down like water and righteousness like a mighty stream." :quotes:


** MLK Jr: I have a dream... that the black person will be judged by the content of his character and not the color of his skin. :quotes:


** MLK Jr: The arc of the moral universe is long, but it bends towards justice. :quotes:


** MLK Jr: When I die, I don't want the person at my funeral to say that I won the Nobel. I want him to say that I tried to serve, that I tried to be right on the war question, that I tried to feed the hungry... If you want to say that I was a drum major, say that I was a drum major for peace, for justice, and for service. All the other shallow things don't matter. :quotes:


** MLK Jr: Why should I aim for personal happiness when so much depends on the contributions I make? :quotes:


** MLK Jr: It is obvious today that America has defaulted on this promissory note insofar as her citizens of color are concerned. Instead of honoring this sacred obligation, America has given the Negro people a bad check, a check which has come back marked insufficient funds. :quotes:


* The Rebellious Life of Mrs Rosa Parks by Jeanne Theoharis          :Review:

Rosa Parks was heavily involved in the NAACP Montgomery chapter. She
allied with E. D. Nixon to champion voting rights, registration,
etc. However, she had resigned herself to the fact that not much
progress was being made in spite of her activism.

Just weeks before the bus boycott, she attended a workshop at
Highlander, Alabama, where whites and blacks lived together in a
communal setting. She was very quiet during the workshop and was
mentally wrestling with the fatigue she felt from all her previous
activism not bearing fruit. However, she was inspired to action by the
workshop.

Just days before the bus boycott, the case of Emmett Till, a Chicago boy who got
lynched in the south, came to light. His mother insisted on an open
casket, a fact that was reported by the press. Parks was shocked by
this incident and it may have been the final straw leading to the bus
boycott. Many black people from the south were being murdered in this
fashion but the incidents were covered up. Till's murder got
recognition only because he was from the north.

Before Parks, there had been several people who had refused to give up
their seats. They had often been punished, beaten, or shot for this.

On December 1, 1955, Rosa Parks refused to get up from her seat. She
was highly involved in the ensuing boycott that lasted more than a
year. She suffered personally during the period of the boycott. She
and her husband lost their jobs and suffered daily threats through
phone calls. The white establishment and press portrayed her and
others as Communist backers, suggesting that a movement like the bus
boycott could not have been organized by blacks alone.

The movement made a national hero out of MLK but Parks' contribution
was taken at face value. She was portrayed as the tired black woman
who refused to stand up. In the process, the detailed planning that
led to the event was ignored. On many key occasions, she was not
invited to speak while Nixon and King were. Years later, in the March
to Washington, again, the black establishment downplayed the role of
women in the boycott. Although Parks was asked to sit on the stage,
she was not asked to speak. The civil rights leaders had not yet
recognized the valuable role that women played.

Plagued by lack of jobs and poor health due to stress, Rosa mentioned
her situation to several friends. They turned to the Montgomery
Improvement Association (MIA) and the NAACP. However, neither
organization helped monetarily or through employment even with Rosa's
considerable organizational and political skills. After many years of
suffering and threats, the Parks moved to Detroit to be close to
Rosa's brother. Even there, things did not improve until Rosa found a
job with House Representative, John Conyers.

Rosa took on multiple protests including against apartheid in the 80s,
and against military action in response to 9/11.


** Rosa Parks: You have to remain optimistic. When things go bad, you have to tell yourself that this is another phase, another thing to get through. Nothing comes easily. We have to keep on trying, as long as we are alive. :quotes:
