#+FILE: The philosophy of task management
#+FILETAGS: :Work:Tasks:

* Generation of a set of tasks with an offset from a deadline

The following block of code generates a set of TODO tasks with
appropriately scheduled dates from a table of tasks. The table should
contain a set of tasks and the offsets of time you would like the
tasks to be scheduled for. The code will then create TODO tasks in Org
format with scheduled dates that are at offset days away from
start_date (default is the date when the code is executed).

There may be an optional 3rd column. If it exists and if it is
populated for a row, then the task is created only if the text in the
field matches text in the tag.

#+NAME: test_table
| Task 1 | -1 | test_tag |
| Task 2 |    |          |
| Task 3 |  1 |          |

#+NAME: generate_tasks_from_offset
#+BEGIN_SRC python :results output raw replace drawer :var tab = test_table start_date = "" task_time="20:00" tags = ""
  # Generate a list of tasks with scheduled dates in Org format
  #
  # Input list tab contains a list of lists of at most 3 values: name, offset and tag
  #
  # If offset is neither an integer nor blank, it is ignored
  # If it is blank, it is equivalent to 0 offset i.e.
  # the task should be scheduled on start_date.
  #
  # If the string "tag" from tab is contained in the string input "tags", then the task is
  # included, otherwise it is not.
  #
  # start_date should be a string of "YYYY-mm-dd" format or an empty string.
  # If start_date is an empty string, use today's date.

  import datetime, re

  try:
      start_date = datetime.datetime.strptime(start_date, "%Y-%m-%d").date()
  except:
      if len(start_date) == 0:
          start_date = datetime.datetime.today()
      else:
          raise Exception("Could not parse date string %s" % (start_date))

  if len(tags) > 0:
      # Add colon identifiers for tags if it is specified
      tags = ":" + ":".join(tags.split(",")) + ":"

  for t in tab:
      if not t[1]:
          delta = 0
      else:
          if re.match("[-+0-9]+", str(t[1])):
              delta = int(t[1])
          else:
              continue

      task_date = start_date + datetime.timedelta(days = delta)

      if (len(t) <= 2) or (t[2] in tags):
          print(("*** TODO %s    %s\n    SCHEDULED: " + "<" + "%s %s>\n\n") % (t[0], tags,
                                                                               task_date.strftime("%Y-%m-%d %a"), task_time))
#+END_SRC

#+RESULTS: generate_tasks_from_offset


* Possible criteria for prioritization

   One could use the Eisenhower matrix, as described below. Alternately, the
   Effective Altruism organization method for deciding what to work on may be
   useful. The criteria they use are as follows.
   - Scale
   - Solvability
   - Personal fit
   - Neglectedness

   The first two may be particularly useful for prioritizing projects
   and are basically a cost-benefit analysis.

   - Scale or Benefit :: How much potential benefit/value would this
     project bring (to you, to the family etc.) if you completed it?

   - Solvability or Cost :: How much effort/cost would this project
     take to bring to fruition?

   - Personal fit or Uniqueness :: If you didn't solve this problem,
     would someone else solve it just as well? Generally speaking, for
     work that supports poor people or underserved sections (like
     animals), there isn't a large substitution effect i.e. there
     probably aren't many people who would do the job if you
     didn't. If there is someone else who can solve the problem, you
     could consider outsourcing i.e. donate money to them so that they
     can solve it more efficiently.

   NPV analysis can be done to calculate the cost-benefit tradeoff.


* Eisenhower matrix
   :PROPERTIES:
   :CUSTOM_ID: Eisenhower_matrix
   :END:

|---------------+-------------+---------------|
|               | Urgent      | Not urgent    |
|---------------+-------------+---------------|
| Important     | Do it       | Schedule it   |
|---------------+-------------+---------------|
| Not important | Delegate it | Do less of it |
|---------------+-------------+---------------|

Perhaps, for an "Important" but "Not urgent" task, you should prioritize
and then schedule it. Otherwise, how do you know you are using your
time most valuably?


* The calculation of cost and benefit

   In life, we may care about physical health, mental health,
   contributions to community, relations with friends/family and
   wealth. Each of these factors can be assigned a measure of how
   we feel we are doing on that factor at a given time. A composite
   quality of life measure can then be calculated from the individual
   measures. The closest model to this is that of subjective
   well-being or [[../well_being/Positive_psychology.org::#SWB][SWB]].

   The purpose of any life improvement activity, then, is to improve
   that quality of life measure. It becomes the benefit of the
   activity. Using some established metrics similar to
   [[../well_being/Positive_psychology.org::#Cost of one QALY][Cost of one QALY]], the quality of life can be converted into a unit of
   dollars. The cost of the activity can be calculated by first
   measuring hours of effort spent (labor) and investments to be made
   (capital) and converting those to a total cost in dollars. An NPV
   calculation will then allow us to prioritize improvement
   activities.


** Time efficiency calculation

   Assume you could save t units of time per day for the next 3
   years. That converts to roughly t*400 units per year for 3
   years. Using a 10% discount rate, your total savings is t*400*[1 +
   (1/1.1) + (1/1.1)^2] = t*400*2.75 = t*400*(11/4). So, that's the
   upper bound on how much effort you should spend on that
   improvement.

   For instance, to save 1 min/day for 3 years, you can spend up to
   1000 min or 16 hours.


* Execution of task management

   All this philosophy needs to be translated into an execution
   mechanism. This section describes a reasonable execution
   mechanism for tasks.

   This is heavily influenced by David Allen's "Getting Things Done"
   book.


** Tasks and projects

   First, consider projects. Projects have a defined date by which
   they must be completed and a defined deliverable or goal to be
   completed. The deliverable or goal and the reason for the defined
   date should be explainable to someone outside the project
   team. Note that, by definition, recurring activities don't count as
   projects. Those should be considered as tasks.

   Projects get further sub-divided into tasks.


** TODO Book focus time slots and end-of-day updates for tomorrow
   SCHEDULED: <2023-11-06 Mon 16:00 +1w>
   :PROPERTIES:
   :EFFORT: 00:05
   :BENEFIT: 10
   :RATIO: 1.20
   :LAST_REPEAT: [2023-10-31 Tue 07:02]
   :END:
   - State "DONE"       from "TODO"       [2023-10-31 Tue 07:02]
   - State "DONE"       from "WAIT"       [2023-10-29 Sun 11:54]
   - State "DONE"       from "TODO"       [2023-10-17 Tue 06:31]
   - State "DONE"       from "TODO"       [2023-10-09 Mon 11:39]
   - State "DONE"       from "TODO"       [2023-10-03 Tue 12:55]
   - State "DONE"       from "TODO"       [2023-09-27 Wed 10:17]
   - State "DONE"       from "TODO"       [2023-09-19 Tue 16:23]
   - State "DONE"       from "TODO"       [2023-09-11 Mon 15:10]
   - State "DONE"       from "TODO"       [2023-09-04 Mon 10:46]
   - State "DONE"       from "TODO"       [2023-08-28 Mon 17:47]

** TODO Book focus time slots and end-of-day updates for tomorrow
   SCHEDULED: <2023-11-07 Tue 16:00 +1w>
   :PROPERTIES:
   :EFFORT: 00:05
   :BENEFIT: 10
   :RATIO: 1.20
   :LAST_REPEAT: [2023-10-25 Wed 06:15]
   :END:
   - State "DONE"       from "TODO"       [2023-10-25 Wed 06:15]
   - State "DONE"       from "TODO"       [2023-10-17 Tue 06:31]
   - State "DONE"       from "TODO"       [2023-10-10 Tue 09:43]
   - State "DONE"       from "TODO"       [2023-10-03 Tue 20:38]
   - State "DONE"       from "TODO"       [2023-09-27 Wed 10:16]
   - State "DONE"       from "TODO"       [2023-09-19 Tue 17:15]
   - State "DONE"       from "TODO"       [2023-09-13 Wed 06:39]
   - State "DONE"       from "TODO"       [2023-09-05 Tue 16:37]
   - State "DONE"       from "TODO"       [2023-08-29 Tue 10:20]
   - State "DONE"       from "TODO"       [2023-08-22 Tue 20:56]

** TODO Book focus time slots and end-of-day updates for tomorrow
   SCHEDULED: <2023-11-08 Wed 16:00 +1w>
   :PROPERTIES:
   :EFFORT: 00:15
   :BENEFIT: 10
   :RATIO: 0.40
   :LAST_REPEAT: [2023-11-01 Wed 18:10]
   :END:
   - State "DONE"       from "TODO"       [2023-11-01 Wed 18:10]
   - State "DONE"       from "WAIT"       [2023-10-29 Sun 11:53]
   - State "DONE"       from "TODO"       [2023-10-12 Thu 14:25]
   - State "DONE"       from "TODO"       [2023-10-12 Thu 14:25]
   - State "DONE"       from "TODO"       [2023-10-04 Wed 17:09]
   - State "DONE"       from "TODO"       [2023-09-27 Wed 19:24]
   - State "DONE"       from "TODO"       [2023-09-20 Wed 07:43]
   - State "DONE"       from "TODO"       [2023-09-13 Wed 17:08]
   - State "DONE"       from "TODO"       [2023-09-06 Wed 15:22]
   - State "DONE"       from "TODO"       [2023-08-31 Thu 07:02]
   - State "DONE"       from "TODO"       [2023-08-23 Wed 17:07]

** TODO Book focus time slots and end-of-day updates for tomorrow
   SCHEDULED: <2023-11-09 Thu 16:00 +1w>
   :PROPERTIES:
   :EFFORT: 00:15
   :BENEFIT: 10
   :RATIO: 0.40
   :LAST_REPEAT: [2023-11-02 Thu 17:28]
   :END:
   - State "DONE"       from "TODO"       [2023-11-02 Thu 17:28]
   - State "DONE"       from "WAIT"       [2023-10-29 Sun 11:53]
   - State "DONE"       from "TODO"       [2023-10-20 Fri 06:15]
   - State "DONE"       from "TODO"       [2023-10-12 Thu 14:26]
   - State "DONE"       from "TODO"       [2023-10-05 Thu 08:55]
   - State "DONE"       from "TODO"       [2023-09-28 Thu 22:20]
   - State "DONE"       from "TODO"       [2023-09-21 Thu 06:38]
   - State "DONE"       from "TODO"       [2023-09-15 Fri 08:40]
   - State "DONE"       from "TODO"       [2023-09-07 Thu 13:35]
   - State "DONE"       from "TODO"       [2023-08-31 Thu 14:38]
   - State "DONE"       from "TODO"       [2023-08-24 Thu 21:44]

** TODO Book focus time slots and end-of-day updates for tomorrow
   SCHEDULED: <2023-11-05 Sun 16:00 +1w>
   :PROPERTIES:
   :EFFORT: 00:15
   :BENEFIT: 10
   :RATIO: 0.40
   :LAST_REPEAT: [2023-10-29 Sun 15:25]
   :END:
   - State "DONE"       from "WAIT"       [2023-10-29 Sun 15:25]
   - State "DONE"       from "WAIT"       [2023-10-29 Sun 14:07]
   - State "DONE"       from "TODO"       [2023-10-08 Sun 10:47]
   - State "DONE"       from "TODO"       [2023-10-08 Sun 10:47]
   - State "DONE"       from "TODO"       [2023-10-02 Mon 13:06]
   - State "DONE"       from "TODO"       [2023-09-24 Sun 09:14]
   - State "DONE"       from "TODO"       [2023-09-17 Sun 11:38]
   - State "DONE"       from "TODO"       [2023-09-10 Sun 14:30]
   - State "DONE"       from "TODO"       [2023-09-04 Mon 10:48]
   - State "DONE"       from "TODO"       [2023-08-27 Sun 09:37]
