#+TITLE: The science of happiness and well-being
#+FILETAGS: :Science:Psychology:
#+STARTUP: overview, hideallblocks

* Subjective Well-Being or Happiness                                 :Review:

A related concept within the field of positive psychology is
Subjective Well-Being (SWB), pioneered by Ed Diener. Diener suggests
that SWB consists of two components, Affective Balance and Life
Satisfaction. The SWB score is the sum of the two scores.


** Affective Balance

Affective balance is the difference between positive affects or
feelings and negative affects. This is a measure of the moods of a
person and is emotional in nature. An example measure for Affective
Balance is the [[https://en.wikipedia.org/wiki/Positive_and_Negative_Affect_Schedule][Positive and Negative Affect Schedule]] (PANAS).

The brain has a negativity bias. We feel the loss of something more
sharply than the gain of an equal amount. Also, negative feelings are
generated much faster through the amygdala than positive feelings.

Lack of control over factors such as noise and commute time can cause
unhappiness.


** Life Satisfaction

Life Satisfaction (LS) is the satisfaction with important life
domains - society, work, and leisure. This is a cognitive measure
i.e. it is how you would evaluate life if you stepped back to reflect
on it. Life Satisfaction is more long-term while Affective Balance can
show short-term fluctuations.

One of the most important influences on LS is social
relationships. People who score high on LS tend to have close and
supportive family and friends, whereas those who do not have close
friends and family are more likely to be dissatisfied.

Another factor is work or, more generallly, performance in an important role
such as homemaker or grandparent. When the person enjoys their work,
and feels that it is meaningful and important, it increases their
LS. When work is going poorly because of bad external
circumstances or a poor fit with the person’s strengths, this can
lower LS.

Human beings generally feel pleasure from working towards a goal. The
goal has to be challenging but achievable and they should get regular
feedback. This allows them to achieve a state of flow. However, they
do not gain much pleasure after having achieved the goal although they
perceive that there is pleasure to be gained after achieving the
goal. Eg. winning a lottery, getting your ideal job etc. This is
analogous to the movie "Memento" where the protagonist continually
sets new goals to challenge himself.

A third factor that influences the LS of most people is
personal – satisfaction with the self, religious or spiritual life,
learning and growth, and leisure. For many people, these are sources of
satisfaction. However, when these sources of personal worth are
frustrated, they can be powerful sources of dissatisfaction.

There could be additional sources of satisfaction and dissatisfaction
– common sources such as health and other sources that
are unique to each individual. Most people know the factors that lead
to their satisfaction or dissatisfaction, although a person’s
temperament – a general tendency to be happy or unhappy – can color
their responses. This temperament is highly correlated with genes.

There is no single key to LS. However, a dissatisfied
person can increase their LS with time and effort. For
instance, people who suffer a loss recover over time. People who have
dissatisfaction in any one domain often make changes over time that
will increase their satisfaction. If a person is chronically
dissatisfied, they should look within themselves and develop more
positive attitudes to life and the world.

Buddha said that happiness comes from within. It cannot be achieved by
making the outside world conform to your wishes. Modern positive
psychology agrees.


* Quantitative measurements of quality of life                       :Review:

   A commonly used quantitative measurement of life is
   [[https://en.wikipedia.org/wiki/Quality-adjusted_life_year][Quality-adjusted life year]] or QALY. A QALY measure of 1.0 means a
   year of perfect health while values below
   that mean less than perfect health or quality of life. A value of 0
   represents death. Different interventions can be measured by
   summing up the resulting measures over the number of years of life
   that they provide.

   [[https://www.wsj.com/articles/obscure-model-puts-a-price-on-good-healthand-drives-down-drug-costs-11572885123][This article]] talks about the use of QALYs by a research
   organization called ICER in the US and how it could reduce drug
   prices. While other countries have adopted QALY as a measure, the
   US has not yet.


** Cost of QALY                                                      :Review:
  :PROPERTIES:
  :CUSTOM_ID: Cost of one QALY
  :END:

  From the [[ https://www.wsj.com/articles/obscure-model-puts-a-price-on-good-healthand-drives-down-drug-costs-11572885123][WSJ article]], ICER puts the cost of one QALY in the US at
  $150,000. A graph of QALYs used by other countries is in the
  article. The approach of using QALYs was first established in the
  UK.


** John Donne: No man is an island, entire of itself; ...therefore never send to know for whom the bells tolls; it tolls for thee. :quotes:


* References

- The Happiness Hypothesis, Jonathan Haidt
- Happiness, Edward Diener and Robert Biswas-Diener
- The How of Happiness, Sonja Lyubomirsky
