#+Title: Notes on podcasts and other content from Manager Tools
#+FILETAGS: :Career:Manager:

* Leader's intent

  [[https://www.manager-tools.com/2015/08/leaders-intent-part-1-hall-fame-guidance][Link to podcast]]

  Communicate less about the how and more about the why.

  This is the only way to get growth out of your team.

  Communicate your plans and why. For instance, if you are looking for
  cost-cutting, communicate at a high-level why costs need to be cut
  and roughly how much. You want to stay out of the weeds in terms of
  details and communicate only the intent.


** Eisenhower: Planning is everything; plans are nothing.            :quotes:


** Manager tools: Good judgement comes from experience, experience comes from bad judgement. :quotes:


* My direct is resigning

   [[https://www.manager-tools.com/2014/10/my-direct-resigning-chapter-1-never-counter-offer-part-1-hall-fame-guidance][Podcast link]]

   The two things a manager are responsible for are results and
   retention.


** Congratulate them first!

   We think of the negatives of the person leaving the job and become
   defensive. Many companies don't manage your careers, people are now
   more responsible for their own careers. They have gone out of their
   way to do a resume and interview. So, they've achieved something. Say
   "Congratulations! Tell me more about the offer you have!"


** Gather information

   At this point, the direct has done a lot of work to get a
   counter-offer without your information. You may use words like:
   "Find out more, tell me the whole story: your job, responsibilities, etc."

   Managers will never be able to make directs happy if they are
   focused on just getting a better salary.


** Do not make a counter-offer
