#+TITLE: Objectives and Key Results (OKRs)
#+FILETAGS: :Management:
#+STARTUP: overview

* What are OKRs?                                                     :Review:

Objectives and Key Results (OKRs) are a methodology to make progress
on a business strategy.

Andy Grove first conceived them and
described them in the book titled "High-output management". John Doerr
then picked them up and popularized them through the book "Measure
what matters" and through his company, the Doerr
consulting practice. His thinking influenced the founders at Google
and Google is credited with [[https://www.whatmatters.com/resources/google-okr-playbook][implementing OKRs at scale]].


** OKRs vs KPIs

Roughly speaking, KPIs measure certain key metrics. OKRs, on the
other hand, combine the measurement and optimization of those
metrics towards an overall goal.

See a detailed comparison [[https://www.whatmatters.com/resources/difference-between-okr-kpi][here]].


** OKR scoring

For all Key Results, completion is 100% if the target is hit. It
reduces by 20% for each unit we do worse and increases by 10% for
each unit we do better. For example, for the first target, if the
average achieved is 7 days, the completion rate will be 80%. If it
is 5 days, the completion rate will be 110%.

The completion rate for each KR will always be >= 0%.

The average completion rate across all KRs for one objective will
always be <= 100%.

The OKRs for Q3 are as follows.


*** Objective 1

- Deals are moved from "Stage 1" to "Stage 4" within 4 calendar
  weeks.

- SoWs are provided within 1 calendar week from the request.


*** Objective 2

- At least 4 hours of training courses/team member are completed in
  Q3.

- 10% or fewer of estimated story points are incomplete at the end of
  the sprint.
