#+Title: Automatic setup of performance review steps
#+Author: Dilip Warrier

In my organization, we typically have informal quarterly performance
reviews and a formal performance review at the end of the
fiscal year. There are a set of steps for each performance review. In
this note, we setup the tasks that need to be executed in each cycle.

This table contains the set of tasks that need to be run. For each
task, an offset can be specified that states when the task should be
scheduled relative to a base date.

#+NAME: task_table
|------------------------------------------------------------------------------+---------------------------|
| Task title                                                                   | Number of days from start |
|------------------------------------------------------------------------------+---------------------------|
| Make 1-1s with directs 1 hour to do quarterly goal and IDP reviews           |                           |
| Make 1-1s with directs 1 hour to do quarterly goal and IDP reviews           |                           |
| Create tasks for directs and send message to update and submit goals and IDP |                         5 |
| Request quick feedback on directs from peers                                 |                        70 |
| Send a poll to get feedback on quarterly performance review process          |                       110 |
| Complete my quarterly performance review                                     |                       100 |
|------------------------------------------------------------------------------+---------------------------|

The following block of code generates a set of TODO tasks with
appropriately scheduled dates to handle all the tasks for the
quarterly performance reviews.

The variable start_date should be updated to reflect the base date
from which the tasks are offset.

#+BEGIN_SRC python :results output raw :var tab = task_table start_date = "2021-07-01"
  import datetime, re

  start_date = datetime.datetime.strptime(start_date, "%Y-%m-%d").date()
  for t in tab:
      if t[1]:
          delta = t[1]
      else:
          delta = 0
      task_date = start_date + datetime.timedelta(days = delta)
      print("*** TODO %s\nSCHEDULED: <%s>\n" % (t[0], task_date.strftime("%Y-%m-%d")))
#+END_SRC

#+RESULTS:
*** TODO Send a poll to get feedback on quarterly performance review process
SCHEDULED: <2021-07-20>

*** TODO Complete my quarterly performance review
SCHEDULED: <2021-07-12>

The following task is setup to remind me to run code and generate a
later set of tasks.

** TODO Setup quarterly performance review task list                   :Bose:
   SCHEDULED: <2021-07-20 +3m>
