#+title: Team and inter-personal communication
#+FILETAGS: :Manager:
#+STARTUP: content

* Introduction

  Post the pandemic of 2020-21, teams are increasingly working
  remotely. This is generally a healthy phenomenon. It allows us to
  find talented people irrespective of where they choose to live. It
  encourages diversity of thought as people in different locations may
  think differently about issues. It eliminates the wasteful activity
  of commuting from your home to your workplace, thus saving time,
  personal energy and carbon emissions.

  On the negative side, working with team members who are not near you
  has not been evolutionarily programmed into you. Also, working with
  remote teams can potentially wear you out due to different time
  zones. This can lead to added work-related stress. To mitigate these
  disadvantages, we must cultivate some habits to make it a better
  experience. This note suggests some guidelines on improving the
  overall remote co-working experience.


* Synchronous and asynchronous communication                         :Review:

  [[https://medium.com/levelshealth/how-to-intentionally-structure-scale-company-communications-2c4774e1f8c8][This post]] describes a thoughtful approach to team communication.

  Gitlab also has a [[https://about.gitlab.com/handbook/communication/][memo on the topic]].


* Communicating across cultures


** Holding meetings with Japanese/Korean colleagues or partners

   Their English is generally quite poor and they're sensitive to that.

   Please slow down your pace of speaking by at least 50%.

   Please reduce the number of slides accordingly. For example, if the
standard is 1 slide every 3 minutes, assume that with an Asian
audience, it will be 1 slide every 6 minutes.

Please avoid local idioms that may not make sense outside the US.

Please pause at the end of each slide and encourage questions.

Please refrain from asking "Did you understand what I said?" or the equivalent because it comes across as condescending. Instead, you could try "What is your opinion on this?"

They are generally very hierarchical in structure. There will be a top
person in the meeting who will express his opinion infrequently but
his opinion will matter a lot. Please understand and note who that
person is. Please don't challenge that person openly. Try instead to
ask questions to understand his/her perspective.


* Meeting etiquette                                                  :Review:

  If you need to schedule a meeting with colleagues, please feel free
  to do so.  However, meetings are hard to schedule. Hence, we request
  that you follow discipline regarding the creation, planning and
  running of meetings. This SOP guides you through the process.

  As far as possible, ensure that your meeting doesn't conflict with
  people's blocked time slots or focus time slots. If it does, then
  you should be OK with their not attending the meeting. Check
  everyone's schedule carefully before booking a meeting.  If you
  absolutely must schedule a meeting on top of an existing meeting,
  reach out to those people ahead of time and apologize and ask if
  they can move their existing meeting.

  Set up your calendar to leave breathing room between meetings -
  25-minute meetings instead of 30, 50-minute meetings instead of 60.


** Hosting a meeting

   Plan an agenda and publish it.  Make sure everyone knows what you
   need to talk about.  If your agenda is short, you can put it in the
   calendar invitation. If it's a long agenda, write up a Wiki page
   and provide a link to it in the calendar invitation.

   Be prepared and have the material for the meeting ready.

   If another conflict comes up, please make sure you delete or reschedule the
   meeting. Not showing up for a meeting that you organized is
   unprofessional and makes your colleagues grumpy.

   Stick to the agenda.  If you need to plan another meeting for
   additional topics, plan another meeting. If an attendee introduces
   a new topic, politely suggest that it should go in the parking lot
   to be addressed later and stick to the previous agenda.

   Capture action items (who does what by when?) and track them to
   completion after the meeting.


** Attending a meeting

   Make sure that you respond to meeting invitations with a "Yes",
   "No" or "Maybe". If your response is "No", please send a polite
   note as to why you can't make it. Bonus points if you "propose a new time".

   Be punctual. Show up a couple of minutes before the meeting so that
   the actual agenda of the meeting can be started on time.

   You are free to leave the meeting at the scheduled end time even if
   there is an ongoing conversation. That way, meeting delays don't stack
   up over the course of the day.


* Holding a team workshop                                            :Review:


** 1 month before

   Prepare to spend roughly 10% of the attendee-hours during the workshop
   in planning for the workshop. For instance, if you invite 10 people
   for 1 day, you should plan for 1 person-day of planning effort.

   Decide agenda & attendees for workshop

   Decide if you need external facilitators

   Setup Outlook invitations

   Arrange travel plans


** 1 week before

   Hold pre-workshop meeting

   Share agenda

   Clarify homework to be done before the workshop

   Create templates for easy reporting out for the teams

   Setup Survey Monkey survey for each day

   Setup guidelines for discussion:
   - Remember that some attendees may be remote.
     + Speak clearly and loudly so that they can hear
     + If you work on a physical whiteboard, aim a camera at it
     + Pause frequently to include them in the conversation

   - Have a healthy discussion and, then, be prepared to come to a
     decision. If necessary, the responsible person will break a tie
     and make a decision. When that happens, please support the
     decision going forward.

   - When a decision is made,
     be flexible. Decide whether you have a strong enough opinion that you
     want to block the action. This should happen rarely.

   - Humor is mandatory :)

   - Everyone except for the presenter and note taker - please turn
     off laptops and mobile phones

   - There will be breaks with fixed times. Please be back from breaks
     on time to keep the meetings efficient.


** 1 day before

   - Reminder email to travel to workshop

   - Get the survey results from the last workshop and review them in
     the introduction


** During the workshop

   Prepare report out

   If there are multiple teams, reports need to be reconciled to form final report

   Get feedback using Survey Monkey on each day how the workshop is going


** 1 day after

   Email thanking attendees, send location of meeting notes, followup action items

   Create survey and get feedback


* Brainstorming                                                      :Review:

  In his six thinking hats method, De Bono recommends that all members
  of a team should think in one direction at a time. However, they
  should alternate the direction every few minutes.

  The direction is determined by the hat that is worn, green hat, blue
  hat, etc.

  https://www.atlassian.com/blog/productivity/six-thinking-hats
