#+title: Team communication
#+FILETAGS: :Manager:Learning:
#+STARTUP: content

* Introduction

  Post the pandemic of 2020-21, teams are increasingly working
  remotely. This is in general a healthy phenomenon. It allows us to
  find talented people irrespective of where they choose to live. It
  encourages diversity of thought as people in different locations may
  think differently about issues. It eliminates the wasteful activity of
  commuting from your home to your workplace, thus saving time, personal
  energy and carbon emissions.

  On the negative side, working with team members who are not near you
  has not been evolutionarily programmed into you. Also, working with
  remote teams can potentially wear you out due to different time
  zones. This can lead to added work-related stress. To mitigate these
  disadvantages, we must cultivate some habits to make it a better
  experience. This note suggests some guidelines on improving the
  overall remote co-working experience.


* Holding a team workshop


** 1 month before

   Prepare to spend roughly 10% of the attendee-hours during the workshop
   in planning for the workshop. For instance, if you invite 10 people
   for 1 day, you should plan for 1 person-day of planning effort.

   Decide agenda & attendees for workshop

   Decide if you need external facilitators

   Setup Outlook invitations

   Arrange travel plans


** 1 week before

   Hold pre-workshop meeting

   Share agenda

   Clarify homework to be done before the workshop

   Create templates for easy reporting out for the teams

   Setup Survey Monkey survey for each day

   Setup guidelines for discussion:
   - JENTM (just enough, not too much)
   - Have a healthy discussion then decide whether you have a strong enough opinion that you want to block the action (Be flexible)
   - Humor is mandatory
   - Laptops/mobile will be turned off
   - There will be breaks with fixed times and timer running on the laptop


** 1 day before

   Reminder email to travel to workshop


** During workshop

   Prepare report out

   If there are multiple teams, reports need to be reconciled to form final report

   Get feedback using Survey Monkey on each day how the workshop is going


** 1 day after

   Email thanking attendees, send location of meeting notes, followup action items

   Create survey and get feedback


* Group brainstorming through De Bono's six-hat thinking

  De Bono recommends that all members of a team should think in one
  direction at a time. However, they should alternate the direction
  every few minutes.

  The direction is determined by the hat that is worn, green hat, blue
  hat, etc.

  https://www.atlassian.com/blog/productivity/six-thinking-hats


* Synchronous and asynchronous communication

  [[https://medium.com/levelshealth/how-to-intentionally-structure-scale-company-communications-2c4774e1f8c8][This post]] describes a thoughtful approach to team communication.

  Gitlab also has a [[https://about.gitlab.com/handbook/communication/][memo on the topic]].
