#+title: Team communication
#+FILETAGS: :Manager:

* Introduction

Post the pandemic of 2020-21, teams are increasingly working
remotely. This is in general a healthy phenomenon. It allows us to
find talented people irrespective of where they choose to live. It
encourages diversity of thought as people in different locations may
think differently about issues. It eliminates the wasteful activity of
commuting from your home to your workplace, thus saving time, personal
energy and carbon emissions.

On the negative side, working with team members who are not near you
has not been evolutionarily programmed into you. Also, working with remote
teams can potentially wear you out due to different time zones. This
can lead to added work-related stress. To mitigate these disadvantages, we must cultivate
some habits to make it a better experience. This note suggests some
guidelines on improving the overall remote co-working experience.


* Synchronous and asynchronous communication


* Town hall meetings

  Town hall meetings are a good way to broadcast information, discuss
  financial results, have detailed Q&A etc. I conduct town halls once
  every quarter.


** Task list for town hall meetings [0/7]


*** TODO Ask team to setup games/puzzles etc. for town hall
    SCHEDULED: <2022-01-25 Tue 08:00 +12w>


*** TODO Setup Slido for questions and post-meeting survey to be submitted in town hall
    SCHEDULED: <2022-01-26 Wed 08:00 +12w>


*** TODO Setup food if needed for town hall
    SCHEDULED: <2022-01-26 Wed 08:00 +12w>


*** TODO Ask someone to give spotlight presentation in town hall
    SCHEDULED: <2022-01-26 Wed 08:00 +12w>


*** TODO Setup updates and prep financial information slides for town hall
    SCHEDULED: <2022-01-26 Wed 08:00 +12w>


*** TODO Answer questions left-over from town hall
    SCHEDULED: <2022-02-08 Tue 08:00 +12w>



*** TODO Give recognition for good questions and game organizers in town hall
    SCHEDULED: <2021-12-02 Thu 08:00 +12w>


*** TODO Release post-meeting survey results from town hall
    SCHEDULED: <2022-02-10 Thu 08:00 +3m>


* Task list


** TODO Work on asynchronous comm document                         :Learning:
   :PROPERTIES:
   :Effort:   01:00
   :END:
